### ISSUE TITLE
Declaración Tablas

### ISSUE THREAD

**Issue by clementeross** [IIC2413/Syllabus-2019-1#10]
Hola! La declaración de las tablas es necesario escribirlas en álgebra relacional? O podemos declararlas en cualquier formato mientras sea claro y se resalten las "primary keys"?

**Comment by nivek0o0** [comment]
Hola!
Pueden hacer la declaración en el formato que quieran, aunque se sugiere seguir el que se ha utilizado en las Actividades (p.e. SQL con Capitanes, Botes y Reservas).

Como bien dices es muy importante que quede claro el tipo de dato de cada atributo y la primary key.
