### ISSUE TITLE
Pregunta #5 Ayudantia I2

### ISSUE THREAD

**Issue by tacorrea** [IIC2413/Syllabus-2019-1#103]
Hola,
Tengo dudas con la pregunta 5, ¿alguna respuesta disponible?
Saludos

**Comment by chocopiano** [comment]
x2, Saludos

**Comment by ghost** [comment]
x3, saludos

**Comment by chocopiano** [comment]
O alguna orientación, en la ayudantía no se alcanzo a ver. Por favor!

**Comment by alanezz** [comment]
Hola,

Se trata de programar el algoritmo de recursión más o menos a mano. La idea es la siguiente.

1. Creo una tabla auxiliar donde voy guardando las ciudades alcanzables entre sí. En la primera iteración esta tabla tiene los caminos de largo 1.
2. En las siguientes iteraciones hago el join entre la tabla original y la tabla recursiva, y voy añadiendo los nuevos caminos (largo 2, 3, etc.) a la tabla auxiliar.
3. Si en algún momento el número de tuplas de la tabla auxiliar no cambió de iteración en iteración, salgo del procedimiento.
4. Finalmente, retorno la consulta sobre la tabla auxiliar.

Saludos!

**Comment by chocopiano** [comment]
Gracias!
