### ISSUE TITLE
[i2] I2 2017-2 PREGUNTA 1C

### ISSUE THREAD

**Issue by chocopiano** [IIC2413/Syllabus-2019-1#104]
Alguien sabe que se debe hacer en esa pregunta?
Considere las tablas A(i int) y B(i int). Escriba un trigger que ante cada inserci ́on de un elemento en la tabla B, verifique que ese elemento no est ́a presente en la tabla A.

**Comment by alanezz** [comment]
Hola,

Esa materia ya no la vemos.

Saludos.
