### ISSUE TITLE
Dependencias funcionales actividad

### ISSUE THREAD

**Issue by cacoos** [IIC2413/Syllabus-2019-1#105]
Hola!

Cómo puedo hacer el siguiente ejercicio? Aparte de sacar _isbn_ como key, no veo como podría arreglarlo.

Gracias de antemano!
![image](https://user-images.githubusercontent.com/30879716/57405545-b8c8ed00-71ac-11e9-8bd9-60c3e8373b14.png)

**Comment by felipegarcia98** [comment]
Por aca pensabamos que se podia sacar el cardnum de orders

**Comment by alanezz** [comment]
Hola,

El problema lo tiene la relación `Orders`. Esto porque el `ordernum` te determina el `cid`, `cardnum` y el `order_date`. Recordemos además que el `ship_date` es distinto para cada libro (piensa en Amazon, si haces un pedido con muchos libros, estos pueden llegar en distintos días).

La dependencia anterior rompe BCNF, así que descomponemos `Orders` en dos tablas:

`Orders(ordernum, cid, cardnum, order_date, PRIMARY KEY(ordernum))`
`Orderlist(ordernum, isbn, qty, ship_date, PRIMARY KEY(ordernum, isbn))`

En donde cada tabla tiene sólo las dependencias funcionales que te dan las llaves, por lo que ahora ambas están en BCNF.

Saludos.

**Comment by cacoos** [comment]
Muchas gracias!
