### ISSUE TITLE
Busqueda Entrega 3

### ISSUE THREAD

**Issue by csolguin** [IIC2413/Syllabus-2019-1#107]
Hola,
Para realizar la busqueda,¿Es necesario hacerlo como una consulta con "LIKE" y dirigirlo a otra pagina,  o puedo hacerlo de forma interactiva con un JQuery en el mismo html?
De antemano muchas gracias.

**Comment by alanezz** [comment]
Hola,

No es obligación hacerlo de forma interactiva, pero mientras más _user friendly_ sea, mejor (y así puedes aspirar al bonus).

Saludos.
