### ISSUE TITLE
Entrega 3: Modificar Base de datos

### ISSUE THREAD

**Issue by bgsamilla** [IIC2413/Syllabus-2019-1#108]
Tenemos un problema; en una de las bases de datos falta información importante.....
Podemos agregarla modificando la base de datos de ese servidor, el problema es que para hacerlo de manera correcta (En BCNF) dejaría el trabajo de la entrega 2 de ese grupo sin funcionar y el enunciado dice que los links deben seguir funcionando y no podemos modificar los archivos de la entrega 2 ....
¿Entonces que podemos hacer? 
¿Crear una base de datos 2 para esta entrega? (Es decir dejar las tablas actuales para que funcione la entrega 2 y crear otras versiones para la entrega 3)
¿Arreglarlo a la mala? (Olvidar BCNF y forzar que ambas entregas funcionen con las tablas actuales modificadas un poco)
Vale decir que todo se haría en ese mismo servidor, no estamos pensando en unificar las bases de datos en uno solo.

**Comment by alanezz** [comment]
Hola,

Puedes usar alguna de las bases de datos que les dimos para los procedimientos almacenados como una base de datos para esta entrega, mientras lo señales en el readme.

Saludos.
