### ISSUE TITLE
Duda logout

### ISSUE THREAD

**Issue by arbiocanpion** [IIC2413/Syllabus-2019-1#109]
Hola!, tengo una duda respecto a la entrega tres del proyecto, específicamente, respecto a si es necesario tener un logout en la página.

**Comment by alanezz** [comment]
Hola,

La idea es que la aplicación se acerque a una que usarías en la realidad. Yo al menos no me imagino usando una aplicación que no tenga logout, además que esto debería ser muy sencillo de hacer.

Saludos.

**Comment by arbiocanpion** [comment]
Gracias!
