### ISSUE TITLE
Convencion nombres de id, y Duda agencia

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2413/Syllabus-2019-1#11]
Primero queria saber cual es la correcta manera de nombrar el id, siguiendo convencion usada en actividad 1 el id de Usuario seria uid, pero que pasa cuando existen don tablas que empiezan con la misma letra, seria correcto nombrar segundo id uid2.

Y tambien para Agencias se señala que Pueden estar en mas de una region, es correcto que tenga una columna Region que acepte listas, o lo correcto es crear otra tabla que me entrege esa informacion

Gracias

**Comment by nivek0o0** [comment]
Hola,
la manera correcta de nombrar los atributos será aquella que sea más intuitiva para ti y para los usuarios de tu DB. En general se usa ID,  pero algunos escriben "uid" para evitar que especificar la tabla en las condiciones (Tabla1.id = Tabla2.id  vs  uid = pid). En caso de que optes por esta última forma, podrías añadir más letras que la "u" y separar con guión bajo, como por ejemplo user_id & uxxx_id.

Respecto a la segunda pregunta, si bien es posible guardar arreglos en Postgres, es una mala práctica porque dificulta la mantención de la tabla y te dificulta las consultas. Además tu BD dejaría de estar normalizada, que es un requisito en el proyecto a partir de la entrega 2. Es un desafío para ustedes encontrar la forma de solucionar esto.

Saludos!
