### ISSUE TITLE
Funcion usuarios

### ISSUE THREAD

**Issue by gejohow** [IIC2413/Syllabus-2019-1#110]
Hola! Escribo para preguntar la función de los usuarios relacionado con el login. Los usuarios de la base de datos dada son los unicos que se pueden registrar o los unicos que pueden hacer login, etc. ? En esos casos habria que darle alguna contraseña?
En caso contrario cual es el procedimiento a seguir con estos usuarios ya dados.
Gracias!

**Comment by valerojasm** [comment]
Hola!

Lo importante es que los usuarios puedan hacer login para ver su información, así que si agregan una columna con contraseñas random o si crean un mecanismo de registro da igual mientras se mantenga que los usuarios existan en la base de datos.

Saludos!
