### ISSUE TITLE
Búsqueda entrega 3

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2413/Syllabus-2019-1#111]
Hola! 
El buscador que debemos hacer, ¿debe ser uno para todo? ¿O un buscador para hoteles, otro para parques, etc?
Además, ¿el buscador debe poder usarlo cualquier persona en la página o solo los que iniciaron sesión?

Saludos y gracias

**Comment by valerojasm** [comment]
Hola!

Queda a tu criterio si el buscador es uno solo o uno por entidad, lo importante es que se pueda buscar por cada una de ellas y que sea claro su uso. En cuanto a tu segunda pregunta, ya que cualquier usuario debería poder navegar por tu aplicación sería más lógico que cualquiera pueda buscar.

Saludos!
