### ISSUE TITLE
Insertar contraseñas

### ISSUE THREAD

**Issue by Franco1605** [IIC2413/Syllabus-2019-1#112]
Hola ! mi pregunta es si podemos crear una tabla nueva que contenga el id del usuario y la contraseña respectiva para poder modelar el inicio de sesión. He intentado agregar una columna a la tabla usuario, pero no hallo la forma de insertar todas las contraseñas en esa columna.
Hay alguna forma de hacer lo anterior de forma rápida ?
O es mejor la primera opción ?

**Comment by alanezz** [comment]
Hola,

Te recomendaría tomar el csv, agregar una columna contraseña e importar la tabla nuevamente. Sino puedes hacerlo rápido con un procedimiento almacenado.

Saludos.
