### ISSUE TITLE
Fechas de las reservas

### ISSUE THREAD

**Issue by jfacuse** [IIC2413/Syllabus-2019-1#113]
Hola! Para la entrega 3 es necesario fijarse que al hacer una reserva a alguna habitacion no haya otra reserva a la misma fecha ? Pregunto porque no se si la base de datos a dada es consistente con eso jajaj. Saludos

**Comment by alanezz** [comment]
Hola,

Sí, es lo ideal. La base de datos debería ser consistente con eso.

Saludos.
