### ISSUE TITLE
Entrega 3: Problema al agregar datos a tabla

### ISSUE THREAD

**Issue by lucasvsj** [IIC2413/Syllabus-2019-1#115]
Buenas
Al momento de agregar datos a mi tabla existente en el servidor, uso el siguiente código:
$query = "INSERT INTO Usuarios (uid, nombre, nacimiento, correo, nacionalidad, clave) VALUES ('$id', '$usr', '1997-12-20', '$usr'.'@uc.cl', 'Chileno', '$psw')";
$stmt = $this -> db -> prepare($query);
$stmt -> execute();
El código no falla, pero al momento de revisar la tabla, los datos no han sido agregados.
He buscado en internet y todos utilizan el mismo (o una variación mínima del) código.
¿Alguna idea de por qué no agrega los datos?

**Comment by dtmaltrain** [comment]
Hola! tuve el mismo problema, puede que esto te sirva (a mi me sirvió):
http://www.postgresqltutorial.com/postgresql-php/insert/
😃

**Comment by lucasvsj** [comment]
Probé lo mismo y aun así no se realizaron los cambios de los datos en la tabla.
@DaToMC9 a ti te funciono?

**Comment by dtmaltrain** [comment]
sip, usando bindValue 🤔

**Comment by lucasvsj** [comment]
@DaToMC9 tambien lo use y no funcionaba, usaste commit()?

**Comment by cmp831** [comment]
Hola, el error está en la concatenación de strings que tienes dentro de tu string en `$query`, cual no lo puedes usar dentro de un string. Como estan usando php, lo más simple que puedes arreglar esto es literalmente 
```
$query = "INSERT INTO Usuarios (uid, nombre, nacimiento, correo, nacionalidad, clave) VALUES ('$id', '$usr', '1997-12-20', '$usr@uc.cl', 'Chileno', '$psw')";
```
Debe funcionar así.

**Comment by lucasvsj** [comment]
@cmp831 era eso, mil gracias

**Comment by haarenas** [comment]
Hola, estoy teniendo el mismo problema, pero no logro dar con ninguna solucion. Hasta el momento he intentado lo siguiente:
- Intento 1
```
    $query = "INSERT INTO Reservas (resvid, uid, habid, fecha_inicio, fecha_termino) VALUES ('$new_id','$id_usuario','$id_habit','$fecha_inicio','$fecha_termino')";
    $result = $db2 -> prepare($query);
    $result -> execute();
```

- Intento 2
``` 
    $query = "INSERT INTO Reservas (resvid, uid, habid, fecha_inicio, fecha_termino) VALUES (:resvid, :uid, :habid, :fecha_inicio, :fecha_termino)";
    $result = $db2 -> prepare($query);
    $result -> bindValue(':resvid', $new_id);
    $result -> bindValue(':uid', $id_usuario);
    $result -> bindValue(':habid', $id_habit);
    $result -> bindValue(':fecha_inicio', $fecha_inicio);
    $result -> bindValue(':fecha_termino', $fecha_termino);
    $result -> execute();
```


- Intento 3
```
    $db2->beginTransaction();
    $query = "INSERT INTO Reservas (resvid, uid, habid, fecha_inicio, fecha_termino) VALUES (:resvid, :uid, :habid, :fecha_inicio, :fecha_termino)";
    $result = $db2 -> prepare($query);
    $result -> bindValue(':resvid', $new_id);
    $result -> bindValue(':uid', $id_usuario);
    $result -> bindValue(':habid', $id_habit);
    $result -> bindValue(':fecha_inicio', $fecha_inicio);
    $result -> bindValue(':fecha_termino', $fecha_termino);
    $result -> execute();
    $db2->commit();
```

**Comment by lucasvsj** [comment]
@haarenas te falta el ";" al final de las querrys. ej:
$query = "INSERT INTO Reservas (resvid, uid, habid, fecha_inicio, fecha_termino) VALUES ('$new_id','$id_usuario','$id_habit','$fecha_inicio','$fecha_termino');";
