### ISSUE TITLE
Entrega 2 Navegación de Usuario no registrado

### ISSUE THREAD

**Issue by arpincheira** [IIC2413/Syllabus-2019-1#117]
Hola, con mi grupo tenemos una duda acerca del punto de habitaciones disponibles. ¿Para esta consulta deberíamos utilizar la disponibilidad según la fecha actual, crear un calendario que muestre los periodos en que las habitaciones estén reservadas o que el usuario no registrado pueda realizar la búsqueda por fechas con tal de que si cae en un período donde está reservada esta no aparezca al buscar las habitaciones disponibles?

Muchas gracias de antemano

**Comment by alanezz** [comment]
Hola,

Para mí la mejor solución es que al buscar habitaciones no te muestre las que están reservadas, o bien que te las muestre y diga que están reservadas (como en Booking).

Saludos.
