### ISSUE TITLE
modificacion de bases de datos

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2413/Syllabus-2019-1#118]
Probando la base de datos se agregaron nuevos usuarios, reservas, etc. Debo hacer drop a cada base de datos y volver a cargarlas con los datos originales o puedo dejarla asi?

**Comment by valerojasm** [comment]
Hola! 

La idea es que siempre tengas la versión más actualizada de los csv, eso nos facilita la corrección a nosotros también, ya que con esta revisamos sus entregas.
