### ISSUE TITLE
Horario del Examen

### ISSUE THREAD

**Issue by baaldana** [IIC2413/Syllabus-2019-1#119]
Hola,

el examen de bases de datos es el mismo día que el examen de Finanzas (sección de Reyes), que es a las 3:30pm.  Miré el programa de BDD pero no encontré una hora definida. ¿A qué hora será?

Gracias

**Comment by alanezz** [comment]
Hola,

El examen es a las 9:00 y dura hasta las 12:00 más o menos.

Saludos!
