### ISSUE TITLE
Entrega y Evaluación - Bonus SQL

### ISSUE THREAD

**Issue by msmendoza** [IIC2413/Syllabus-2019-1#12]
En el cuestionario de Siding relativo a la Actividad Casen, ¿es necesario adjuntar un **.pdf** con las explicaciones de las consultas o pueden ser incluidas dentro del **.ipynb**?

**Comment by nivek0o0** [comment]
Hola, 
todo debe estar incluido en el jupyter notebook! Por lo tanto, deben entregar 2 archivos, el notebook (.ipynb) y la base de datos (.db)

**Comment by msmendoza** [comment]
Perfect, gracias! 😁
