### ISSUE TITLE
[Entrega 4 / Text Search] - Palabras que son deseables pero no necesarias

### ISSUE THREAD

**Issue by Faalfaro** [IIC2413/Syllabus-2019-1#122]
Hola,
no entiendo esta parte del enunciado, pienso que básicamente es lo mismo que no buscar por nada , ya que si busco filtrando solo por este ítem, me saldan mensajes que tienen esta palabra y también mensajes que no la tienen, es decir, todos. Help.

Saludos!

**Comment by alanezz** [comment]
Hola,

En clases vimos que hay una forma (con comillas dobles) de pedir algo que obligatoriamente tiene que estar. Si algo no va entre comillas, puede eventualmente no aparecer, aunque es bastante raro. De eso se trata una palabra deseable pero no obligatoria.

Saludos.
