### ISSUE TITLE
Duda Guía I3 pregunta 1.c

### ISSUE THREAD

**Issue by fjlopez7** [IIC2413/Syllabus-2019-1#126]
¿Cómo serian los cálculos del numeros de fases y costo I/O en External Merge Sort en el caso optimo? en las diapos de las clases se vio que eran 2 fases y de esa forma el buffer cumple que

B>=N^1/2

Seria ese el buffer optimo?

**Comment by alanezz** [comment]
Hola,

Sí, ese sería el buffer óptimo. Uno en el que al menos caben N^(1/2) páginas.

Saludos.
