### ISSUE TITLE
Duda contenido Costo I/O

### ISSUE THREAD

**Issue by tgarcia5** [IIC2413/Syllabus-2019-1#127]
Hola, estoy bastante confundido con todo el tema de costos, tengo dos dudas principalmente.
1) ¿ La única diferencia entre calcular el costo en un B+ tree clustered y uno unclustered es que se en el unclustered se agrega la cardinalidad de la consulta alfinal?
2) ¿Al calcular el costo con un hash index, como afecta tener menos buckets que el total de tuplas en el cálculo?

**Comment by TamaraCucumides** [comment]
1) Eso depende de los supuestos que estés haciendo (p. ej: cuantos punteros caben por pagina)

2) No tiene sentido hacer un bucket para cada dato (algo asi solo tendria sentido si la función de hash fuera inyectiva, lo cual no es asi [colisiones]) No entiendo a qué va tu preguntanacá, por si puedes elaborar más

**Comment by cacoos** [comment]
Pero independiente de los punteros por página igual tendré que recorrer N punteros (uno por cada tupla) o no?

**Comment by TamaraCucumides** [comment]
Si obvio, pero el costo que nos importa no es el costo de ver distintos punteros, es el costo I/O

En vez de cuantificar cuántos datos estoy leyendo, se cuantifica a cuánts paginas de disco tengo que qcceder para revisar todos esos datos

**Comment by cacoos** [comment]
Entiendo, pero para acceder al dato desde el puntero se cuenta +1 en I/O, o no? entonces se sumarían N finalmente, que es lo que dice la issue

**Comment by TamaraCucumides** [comment]
Sii, eso si. Pero en el clistered igual cuentas los datos cuando accedes a ellos (y ahi tienes que tomar en cuenta cuántos te caben por página). 

Siento que quizás te estoy enredando más, pero en sintesis:
Clustered: Bajar el arbl + acceder a los datos
Unclustered: Bajar el árbol + acceder a los punteros + acceder a los datos
