### ISSUE TITLE
Pregunta 1 Costos I/0

### ISSUE THREAD

**Issue by pablovejar** [IIC2413/Syllabus-2019-1#128]
Hola! Viendo lo que hicimos en la ayudantía del viernes pasado vimos que en la pregunta de costos, la b), al momento de ocupar B+Tree daba un costo de h+ a, siendo a el numero de tuplas que hay entre 100.000 y 200.000. Mi duda es , por qué no se considera el porcentaje de ocupación por páginas y no se suma la cantidad de tuplas? 👀👀 Gracias!

**Comment by TamaraCucumides** [comment]
Hola, el costo que mencionas es del caso unclustered y estamos asumiendo que los a punteros caben en una página de disco. Por otra parte, también nos ponemos en el peor caso de que para cada uno de los a punteros, estos van a "apuntar" a una pagina de disco distinta.
