### ISSUE TITLE
termino de recovery

### ISSUE THREAD

**Issue by aamedinaj** [IIC2413/Syllabus-2019-1#129]
Ok, veo 4 escenarios:
- es UNDO y encontró END CHKP: recovery __parte__ desde START CHKP
- es UNDO y no encontró END CHKP: recovery __parte__ desde la mas antigua de las transacciones del START CHKP

- es REDO y encontró END CHKP: recovery __parte__ desde la mas antigua de las transacciones del START CHKP
- es REDO y no encontró END CHKP: recovery __parte__ desde el primer END CHKP que encuentre (el último END CHK escrito)

y, aun así, en ninguno estoy completamente seguro de __hasta dónde__ se hace recovery

**Comment by TamaraCucumides** [comment]
Al saber desde donde partes, debes ir viendo linea por linea si en cada una hay que hacer undo/redo. Esto lo haces hasta el final del log.

**Comment by lily416** [comment]
Hola 😄

Debes tener en cuenta que cuando leemos el _log file_ leemos desde abajo (la última línea escrita) hasta arriba, por lo que en todos los escenarios se **parte** desde la última acción que se registró en el _log file_ y en cuanto **hasta dónde** leer, depende de los casos presentados antes:
- Es `UNDO` y encontró `END CHKP`: hace el _recovery_ hasta el `START CHKP` relacionado a ese `END CHKP`.
- Es `UNDO` y no encontró `END CHKP`:  hace el _recovery_ hasta la transacción más antigua del último `START CHKP`.
- Es `REDO` y encontró `END CHKP`: hace el _recovery_ hasta la transacción más antigua del `START CHKP`.
- Es `REDO` y no encontró `END CHKP`: hace el _recovery_ de todo el _log file_, es decir, se lee hasta el inicio.

Ojala con esto quede más claro.
Ánimo y éxito con la I3. 💪
