### ISSUE TITLE
Duda Guía Índices(en actividades)

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2413/Syllabus-2019-1#130]
Hola! Tenía dos dudas con respecto a las respuestas de esta guía:

1) Se tienen 10^6 datos y paginas de 10 records. La respuesta de la guía para buscar un dato o todos los datos siempre es 10^5. Por qué no es 10^6? No me hace sentido que revise las paginas en vez de los datos, debido a que pienso que debería meterse a cada página a revisar los datos. 

2) Por otro lado, se tiene un b+tree unclustered, entonces en la pregunta de buscar 1 solo dato sale que cuesta h + 1. Sin embargo, yo pensaría que debiera costar h + 1/M + 1 = h + 2; porque tiene que entrar a la página y luego ahí ir desde el puntero al dato.  También podría entender que con h se llega a la página y de ahí +1 para llegar al dato, pero entonces en ese caso, también para b+Tree, el buscar 50 datos debiera ser h + ((50/M) - 1) + 50. 

Aprovecho de hacer otra duda:

No entiendo muy bien porqué se parte diciendo en el enunciado que cada página tiene 10 records, pero después en la parte de B+Tree se dice que tiene M>10 entradas. A qué se refieren con esto, me lo podrían explicar?

Gracias de antemano!!

**Comment by alanezz** [comment]
Hola,

1. El costo que estamos calculando es el de I/O, que es el número de páginas que llevas a memoria. Para revisar todo tienes que llevar cada página una vez a memoria.
2. Eso lo discutimos en clases. Depende cómo interpretes el h puede ser h+1 o h+2.

Respecto al M, representa la cantidad de punteros que te caben por página. En una página van a caber (en general) más punteros que tuplas, porque las tuplas son "más grandes", por eso uno asume esto.

Saludos.
