### ISSUE TITLE
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

### ISSUE THREAD

**Issue by ftrejoc** [IIC2413/Syllabus-2019-1#131]
Hola! Tratando de probar lo de la ayudantía de APIS, estoy tratando de correr el programa tal cual como eta especificado en la ayudantía. En un principio funciona bien, pero al llegar a la parte cuando el "main.py" es un código grande, me sale el siguiente error:

Traceback (most recent call last):
  File "C:/Users/Felipe/Desktop/bases de datos/Syllabus-2019-1/Ayudantías/AyudantiaAPI/release/main.py", line 12, in <module>
    mongod = subprocess.Popen('mongod', stdout=subprocess.DEVNULL)
  File "C:\Users\Felipe\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Felipe\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

Revise los archivos que ahi mencionan, pero estan todos en orden.
Muchas Gracias!

**Comment by naquiroz** [comment]
Hola! :wave:

La linea de `subprocess` puedes sacarla si te esta tirando errores. Lo que puedes hacer tambien es probar en tu consola si el comando `mongod` funciona. Si no funciona debes cambiarlo al comando correspondiente a tu sistema para poder levantar el servidor de mongo. Por lo general es `mongod` pero hay casos donde no lo es, asi que puedes revisar eso.

Saludos y exito con la entrega! :muscle:
