### ISSUE TITLE
Conexion Remota a MongoDB no funciona

### ISSUE THREAD

**Issue by jfacuse** [IIC2413/Syllabus-2019-1#132]
Hola! Me pasa que cuando trato de conectarme a la base de datos de mongo en el servidor de la u (tal cual como dice el tutorial en la wiki), me deja entrar pero luego no me muestra ninguna de las colecciones que he creado dentro (como si la base de datos estuviera vacía). Se que no esta vacía ya que si entro desde el servidor con localhost si que me aparecen las colecciones que he creado. 
Probe conectandome tanto por la consola como por PyMongo, pero las 2 fallaron en lo mismo. Que se puede hacer aquí ? 
Por mientras simplemente cree la base de datos de los usuarios en mi pc directamente, se vale esto ?
Gracias de antemano!

**Comment by alanezz** [comment]
Hola,

Esta base de datos la vamos a usar en la entrega 5. Para la entrega 4 vamos a testear todo en localhost.
Aunque me llama la atención cuando dices que entras desde el servidor con localhost. A qué te refieres con esto?

Saludos.

**Comment by felipesilvadv** [comment]
Hola

Antes que todo, al parecer lo que hiciste fue crear una base de datos en bases.ing.puc.cl, el servidor remoto de mongo no es ese. Para ingresar a la base de datos nueva debes ingresar como lo especifiqué en el tutorial y a través de esa consola ingresar tus datos. 
Subiré un anuncio donde se explica el número de grupo que corresponde de esa base de datos.
[Aquí](https://docs.google.com/spreadsheets/d/1IWzSGWa6Hf0_hHwkglqf0w7Zs1EfZPBM9IxzO2llEFo/edit?usp=sharing) esta el excel donde se muestra el grupo de mongo que te corresponde.

Saludos

Espero haberte ayudado
