### ISSUE TITLE
Agregar información a messages.json

### ISSUE THREAD

**Issue by gatochico** [IIC2413/Syllabus-2019-1#133]
Hola! Como dice en el enunciado, a messages.json le falta algun id para cada mensaje, y luego dice que queda a nuestro criterio el como arreglarlo. ¿Es legal editar el messages.json dado y agregarle un par llave-valor más y trabajar con eso? 

Saludos!! :cat:

**Comment by naquiroz** [comment]
Hola! De acuerdo a los _footnotes_ del enunciado, eso está permitido.

Éxito con la entrega! :muscle:

**Comment by Mahund** [comment]
Gracias!

**Comment by pablovejar** [comment]
Hola! en el caso de la información delmensaje nuevo, como lo hacemos con lat, y lon y el date? queda a nuestro criterio?

**Comment by Mahund** [comment]
@pablovejar no se si sirva, pero yo deje expresado en el Readme.md que es deber del usuario entregarlos en su request.

**Comment by alanezz** [comment]
Hola,

Pueden asumir lo que quieran, mientras lo especifiquen en el readme y sea razonable.

Saludos!
