### ISSUE TITLE
[Entrega 4 / Text Search] - buscar mensajes que no contienen un conjunto de palabras.

### ISSUE THREAD

**Issue by BlancaMunizaga** [IIC2413/Syllabus-2019-1#134]
Hola! 🐶  Para la consulta de buscar mensajes que no contengan un conjunto de palabras, no hemos logrado hacerlo sin entregarle una palabra que si este en el mensaje, es mas encontramos este link  [https://stackoverflow.com/questions/55227568/how-to-only-exclude-keywords-in-mongodb-text-search](url), en el cual se dice que no es posible buscar un conjunto de palabras que no están en un texto, si no se le entrega alguna que si este. 

Ademas en el enunciado dice que debemos hacerlo por text search y entendimos que no se puede usar regex. Que hacemos? le entregamos una palabra por default o el usuario va entregar una palabra que si esta y luego las que no deben de estar?

muchas gracias! 🙌

**Comment by alanezz** [comment]
Hola,

Pueden suponer que siempre van a entregar algo que sí estará.

Saludos.
