### ISSUE TITLE
Uso de heroku

### ISSUE THREAD

**Issue by fjlopez7** [IIC2413/Syllabus-2019-1#136]
Me surge la duda de como se debe ver la api al subirla a heroku, porque solamente me aparece el error de aplicación (en la pagina que seria https://{nombre_app}.herokuapp.com/) y los documentos que tengo en heroku son 
![image](https://user-images.githubusercontent.com/42160988/59396976-f3e4b000-8d58-11e9-87dc-0156132722e3.png)
Me estaría faltando algún archivo? 
Me falta algún paso (hago algún comando más después del push al repo)?

**Comment by nivek0o0** [comment]
Hola, a simple vista creo que te falta el archivo **requirements.txt**, que Heroku usa para instalar las librerías necesarias.

Eso es distinto al **Pipfile**, que se usa de forma local para instalar las librerías en un entorno controlado.

Revisa esta [Wiki](https://github.com/IIC2413/Syllabus-2019-1/wiki/Tutorial-Deploy-a-Heroku) que hicimos para ver cómo crear ese archivo y para asegurarte que hiciste todos los pasos.

Saludos!

**Comment by fjlopez7** [comment]
Si lo había agregado a heroku, pero no al repo del cual saque la foto (Sigo con el mismo problema). 
Mi duda va a como se yo que la api esta funcionando bien?

**Comment by nivek0o0** [comment]
- La URL que te entrega heroku debe responder bien a las consultas por el navegador
- Cuando haces `git push heroku master`, no debería salir ningun error.
- El dashboard de tu aplicación en Heroku debe decir **build succeeded**.

Si no tienes idea qué está pasando, te aconsejo revisar los logs de la aplicación en heroku.

**Comment by fjlopez7** [comment]
Lo logre solucionar. Tuve que cambiar el nombre del archivo main.py por app.py
