### ISSUE TITLE
[Entrega 5] Failed: error connecting to db server: no reachable servers

### ISSUE THREAD

**Issue by mmsaavedra1** [IIC2413/Syllabus-2019-1#137]
Trato de subir los .json al servidor remoto y al ingresar esta sentencia:

mongoimport -h mongodb://146.155.13.149 --port 27017 -d grupo36 -c messages -u grupo36 -p grupo36 --type json --file messages.json

Mongo me arroja el error:

Failed: error connecting to db server: no reachable servers

Ayuda por fis😭

**Comment by lucasvsj** [comment]
Buenas
Me salia el mismo error hasta que prove esta linea de comando:
mongoimport --uri="mongodb://grupoXX:grupoXX@146.155.13.149:27017/grupoXX?authSource=admin" -c messages --jsonArray m
essages.json
