### ISSUE TITLE
Posibilidad de mover el Examen

### ISSUE THREAD

**Issue by Dyoma3** [IIC2413/Syllabus-2019-1#139]
Habrá alguna posibilidad de mover el examen? Mucha gente quiere ir a ver el eclipse y obviamente es imposible ir a la Serena después de hacer el examen por el taco que va a haber.

**Comment by alanezz** [comment]
Hola,

La fecha del examen la fija la escuela, no depende de mí. Por lo mismo, no existe ninguna posibilidad.

Saludos.
