### ISSUE TITLE
Duda entrega 5 sign-up

### ISSUE THREAD

**Issue by fjlopez7** [IIC2413/Syllabus-2019-1#141]
No es necesario implementar sign-up en la pagina de esta entrega?

**Comment by alanezz** [comment]
Hola,

Tiene que funcionar con el mismo sign-up de la entrega 3.

Saludos.

**Comment by fjlopez7** [comment]
Entonces tendríamos que agregar un método post en la app para crear un usuario?

**Comment by alanezz** [comment]
No, no es necesario logearse en la API, solo del lado de la app de php.

Saludos.

**Comment by fjlopez7** [comment]
Mi duda va a si es que se desea crear un usuario se deben actualizar las bases de datos en postgres y mongo, en donde este último se debería crear una función en la Api para agregar este nuevo usario, la que no estaba solicitada en la entrega 4.

**Comment by nivek0o0** [comment]
Hola @fjlopez7, 

sí es necesario que añadan una nueva ruta POST en la api, para que cuando se cree un nuevo usuario se mantengan consistentes ambas bases de datos y no se caiga la aplicación cuando alguien quiera mandarle un mensaje a un usuario recién creado.

Si bien esa ruta no estaba en la entrega 4, es producto de la integración entre las aplicaciones.
