### ISSUE TITLE
[Poblar Heroku] - Duda

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2413/Syllabus-2019-1#142]
Hola!, hemos estado intentando subir `messages.json`, pero no hemos podido. Es probable que el método que estamos utilizando no es el adecuado. ¿Dónde podemos ver un tutorial para hacer esto?

Saludos!

**Comment by Faalfaro** [comment]
Lo logramos resolver, gracias igual!

**Comment by Mahund** [comment]
@Faalfaro como lo solucionaron?

**Comment by Faalfaro** [comment]
@Mahund en tu app.py o donde tengas la app, donde defines los parámetros de mongo, tienes que cambiar el localhost por 146.155.13.149. Después, para poder subir los .json, tienes que hacer lo que dicen en la issue #137. Lo primero es para que tu app pida los datos a un server que esta en linea(el de la u) y lo segundo es para tener tus datos subidos. Suerte!

**Comment by Mahund** [comment]
@Faalfaro muchas gracias!
