### ISSUE TITLE
[Entrega 5] Error al importar archivos al servidor remoto

### ISSUE THREAD

**Issue by gatochico** [IIC2413/Syllabus-2019-1#143]
Hola! Estoy tratando de poblar el servidor remoto de MongoDB con los archivos .json de la E4. Usé el código que comentó un compañero en la issue #137 y me lanza el siguiente error:

![image](https://user-images.githubusercontent.com/37161120/59965983-84528b80-94e3-11e9-9851-113ee92525ba.png)

Ayuda 😿 y gracias!

**Comment by cacoos** [comment]
Hola!

Me funcionó agregarle --batchSize 1 al final del comando!

**Comment by gatochico** [comment]
TE ADORO GRACIAS! 😻

**Comment by Mahund** [comment]
Porque cierran las issues? :cry:
