### ISSUE TITLE
Busqueda por texto

### ISSUE THREAD

**Issue by mora4** [IIC2413/Syllabus-2019-1#144]
Hola,

En la parte de búsqueda por texto tengo problemas porque no se cual es el límite de palabras/frases que pueden ingresar para la búsqueda y no he podido hacer un form html con cantidades de inputs variables. ¿Podemos asumir que hay un máximo de palabras/frases? O si son cuantas el usuario quiera, ¿hay alguna forma de hacer un form html con indefinida cantidad de inputs? 

Gracias!

**Comment by cmp831** [comment]
Hola, quizás un input que recibe todo puede servir, por ejemplo, separar las palabras con `-`.
Si el usuario ingresa una búsqueda de `hola-como` entonces en tu backend lo puedes manejar como palabras separadas.

**Comment by mora4** [comment]
Buena idea, lo voy a probar!
Muchas gracias!
