### ISSUE TITLE
Tutorial Heroku 

### ISSUE THREAD

**Issue by isavega** [IIC2413/Syllabus-2019-1#146]
Hola,

Estaba probando el tutorial de heroku (https://medium.com/the-andela-way/deploying-a-python-flask-app-to-heroku-41250bda27d0).

Y llegue a la parte de clonar el repositorio https://git.heroku.com/kbucket-api-heroku.git, luego entiendo que debo ejecutar Heroku master. Me pueden detallar esto ultimo?

Ya que me sale el siguiente error en mi aplicación (utilice la misma que la del tutorial). Gracias!

![image](https://user-images.githubusercontent.com/42187168/60071859-9271f900-96e9-11e9-8847-01182be14d6b.png)

**Comment by cmp831** [comment]
Hola, puedes ejecutar `heroku logs --tail` en tu consola como se muestra en la página? Usando ese comando puedes enterarte de los errores generados por la aplicación que montaste.

**Comment by isavega** [comment]
Sale lo siguiente: 

![image](https://user-images.githubusercontent.com/42187168/60130514-5aa89700-9765-11e9-8552-28e18d492827.png)

Creo que mi problema es al ejecutar Heroku master, aca estan mis intentos fallidos jjajajja

![image](https://user-images.githubusercontent.com/42187168/60130621-98a5bb00-9765-11e9-8355-4556fe4dd7f7.png)

Tambien al ingresar al supuesto repositorio de mi app, me sale "Method Not Allowed" 

Muchas gracias!!

**Comment by nivek0o0** [comment]
Hola @isavega 

¿Puedes decirme qué tienes en tu Procfile y qué aparece cuando ejecutas git remote? (ambas cosas)

**Comment by isavega** [comment]
En mi Procfile sale "web: gunicorn app:app"

C:\Users\Isabel Vega\Desktop\bucket_api_heroku>git remote
heroku
origin

**Comment by nivek0o0** [comment]
En el Procfile lo que sale después de `app:` es el nombre del script de python que es ejecutado cuando se inicial el servidor de heroku. En el repositorio del tutorial parece que se llama `run.py` y no `app.py`. Intenta cambiar eso y hacer el deploy de nuevo.

Y ojo! el comando es `git push heroku master`. En tu imagen de intentos pusiste **heruko**

**Comment by isavega** [comment]
Acabo de probar cambiando el Procfile y tampoco funciona :( Despues ejecute los mismo logs de antes.

![image](https://user-images.githubusercontent.com/42187168/60135892-c3e1d780-9770-11e9-9eb1-3bc076871f56.png)

![image](https://user-images.githubusercontent.com/42187168/60135925-e116a600-9770-11e9-89dc-3f6106897eb8.png)

De verdad que muchas gracias!!

**Comment by nivek0o0** [comment]
@isavega Pudiste hacer deploy de la aplicación? (ésta o de la entrega 4)

**Comment by isavega** [comment]
No aun, mantenemos el error

**Comment by nivek0o0** [comment]
Probaron [esto](https://devcenter.heroku.com/articles/error-codes#h14-no-web-dynos-running)?
