### ISSUE TITLE
Duda API entrega 5

### ISSUE THREAD

**Issue by fjlopez7** [IIC2413/Syllabus-2019-1#147]
Se pueden agregar funcionalidades a la API como para que arroje todos los mensajes que recibe un usuario x?

**Comment by nivek0o0** [comment]
Hola, voy a suponer que te refieres a que cuando inicie sesión pueda ver los mensajes recibidos de otro usuario.

Antes de responder me gustaría saber, ¿cuál es el valor de esa funcionalidad?. 
Piensa que en una aplicación de mensajería los mensajes son privados.

**Comment by fjlopez7** [comment]
Es lo que supones.
Me refería al primer punto.
![image](https://user-images.githubusercontent.com/42160988/60311288-8c1b9100-9924-11e9-9c30-943cff026d67.png)
Ya que en la API solo se pedía los mensajes que el usuario con cierto id había enviado.

**Comment by nivek0o0** [comment]
Ahh, el primer punto se refiere a ver **mis** mensajes recibidos.

Probablemente tengan que adaptar la API de la entrega 4 para satisfacer las funcionalidades de la entrega 5, como sucede con el sign-up. #141. Por lo tanto la respuesta a tu pregunta es **sí, pueden modificar la API.**

Para este caso, una alternativa es tratar de encontrar una forma de obtener mis mensajes recibidos utilizando las rutas que ya tienen.

**Comment by fjlopez7** [comment]
Por ahora tengo una función que calcula los recibidos de forma similar a lo que hacia la función que mostraba los mensajes enviados por el usuario.
