### ISSUE TITLE
[Entrega 5] Enviar mensaje a otro usuario

### ISSUE THREAD

**Issue by gatochico** [IIC2413/Syllabus-2019-1#148]
Hola! Para la parte de enviar mensajes a otros usuarios, ¿Hay algún formato específico a seguir? Por ejemplo, puedo asumir que el usuario se sabe el ID de quien recibe su mensaje? O que las latitudes y longitudes pueden ser aleatorias (o tengo que usar ipstack o algo así)? O es todo a mi criterio? 

Gracias! :3

**Comment by nivek0o0** [comment]
Hola @gatochico 

El enunciado no indica cómo se debe implementar el envío de mensajes, por lo tanto queda a tu criterio. 

Sin embargo, te recomiendo hacerlo de la forma más **cómoda**, **usable** y **realista** posible, porque los ayudantes nos fijamos en esos detalles cuando corregimos, lo que influye en la existencia y cantidad del bonus que asignamos.

**Comment by gatochico** [comment]
Gracias!
