### ISSUE TITLE
[Entrega 5] Duda enunciado

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2413/Syllabus-2019-1#149]
Hola! Tenía una duda del enunciado. Sale que hay que subir la API a heroku y consumirla desde la aplicación PHP. Esto se refiere en que en nuestra página http://bases.ing.puc.cl/~grupoXX/ tenemos que implementar la mensajería? Y luego, también implementar en esa misma página la página resumen?

O hay que implementar todo lo anterior también en heroku? 

Gracias!!

**Comment by nivek0o0** [comment]
Hola @miguelramirezv 

La aplicación en Heroku **sólo** debe administrar los mensajes (entregártelos, permitirte crear nuevos, etc). En otras palabras, debe actuar como ayudante o aplicación auxiliar.

Estos mensajes deberán ser obtenidos y renderizados por la aplicación en PHP mediante los json que retornan las llamadas a las rutas implementadas en la app de Heroku.

 La app PHP es la que debe manejar la interacción con los usuarios humanos y debe tener las otras funcionalidades del enunciado 5, 3 y anteriores.
