### ISSUE TITLE
Registro de las transferencias de archivos al Server

### ISSUE THREAD

**Issue by msmendoza** [IIC2413/Syllabus-2019-1#15]
¿Existirá una forma de acceder o ver el tiempo exacto en el que subimos (por ejemplo) la E1 al Server? Tengo entendido que en MacOS con `.bash_history` a lo más puedo ver los comandos que usé en la Terminal pero no el tiempo en que los utilicé.

Es más que nada porque intenté subir una v2 de mi E1 demasiado cerca de las 23:59 (la idea de revisar nuevamente la entrega fluye cerca de estas horas) y no sé si me contará para la evaluación, de todas formas dejé la v1 intacta en caso de tener problemas.

😓😅

**Comment by alanezz** [comment]
Hola,

Si el servidor te dejó subir la entrega, entonces no hay problema.

Saludos.

**Comment by msmendoza** [comment]
Ok, entonces borro la versión antigua.

Gracias!!! 🙌🏽
