### ISSUE TITLE
Method Not Allowed

### ISSUE THREAD

**Issue by ararojas** [IIC2413/Syllabus-2019-1#150]
Hola!
Logré crear el repositorio y al hacer git push heroku master me dice que el deploy se realizó exitosamente, pero al abrir el enlace en el buscador, me dice solamente Method Not Allowed.
¿Cuál podría ser mi error?
Gracias!

**Comment by nivek0o0** [comment]
Hola @ararojas 

El error posiblemente es que estás tratando de acceder con el navegador (que utiliza método GET) a una ruta que no tiene permitido dicho método (tal vez permite solo POST).

Para acceder a rutas distintas de GET lo más sencillo es utilizar Postman.

Confírmame si era esto y lograste resolverlo.
