### ISSUE TITLE
No puedo hacer git push

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2413/Syllabus-2019-1#151]
Hola!
Cree un repositorio con el comando heroku create y creo haberlo hecho bien.
Cuando intento hacer git push heroku master me sale el siguiente error:

remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/python.tgz

Que puede estar pasando? y como puedo saber si cree bien el repositorio? En el tutotial de la Wiki no se explica muy bien como trabajar con el repositorio.
Gracias!

**Comment by nivek0o0** [comment]
Hola @Marialuisaclaro 

¿Tienes subido ese proyecto a un repositorio de github? Para que me lo compartas y poder investigar el origen del error.
