### ISSUE TITLE
[Entrega 5] Duda Búsqueda mensaje

### ISSUE THREAD

**Issue by gatochico** [IIC2413/Syllabus-2019-1#153]
Hola!

Un detalle que no me queda claro del punto 4 de la parte de Consumir API de la entrega... Cuando haga la búsqueda por texto de mensajes, tengo que filtrar a partir de:

a) Los mensajes recibidos del usuario
b) Los mensajes enviados+recibidos del usuario (los que tengan que ver con el user, en general)
c) Todos los mensajes de la base, tengan que ver con el user o no (Sería raro que fuera esto, pero quien sabe...)

Saludos! >:3

**Comment by cmp831** [comment]
La idea es que ustedes consumen su API creada en la entrega 4. Dado que en la entrega 4 se pidió busqueda de mensajes en la base de datos completo, y emitidos por un usuario en particular, pueden asumir que el filtro se realiza sobre el punto a y c (implementar ámbas). Siempre y cuando lo mencionan en la página, o en el readme sobre lo que están filtrando.
