### ISSUE TITLE
[Entrega 5] Ubicaciones de los mensajes emitidos

### ISSUE THREAD

**Issue by jfacuse** [IIC2413/Syllabus-2019-1#155]
Hola! Haciendo la parte de mostrar en el mapa todos los mensajes emitidos por un usuario en cierto rango de fechas, me di cuenta de que todos los mensajes que ha mandado un usuario están en exactamente la misma latitud y longitud, por lo que al final aunque sean varios mensajes en el mapa se ve como si fuera solo 1 (ya que estan solapados en un punto). Esto está bien asi ? De repente pense que era mejor mostrar los mensajes recibidos ya que estos si tienen distintas ubicaciones y por lo tanto el mapa tendría mas sentido. 
Saludos!!

**Comment by nivek0o0** [comment]
Hola @InfiniteDreamX 

Entiendo perfectamente que los datos entregados no ayudan a que las ubicaciones en el mapa se vean bien. Pero no puedes cambiar el requisito a mostrar los mensajes recibidos, porque en ese caso estarías desplegando las ubicaciones de otros usuarios y no del usuario actual, que es lo que buscamos. 

Además, esperamos que después de enviar un mensaje podamos ver una nueva marca en el mapa, lo que no ocurriría si muestras mensajes recibidos.

Lo que podrías hacer es separar manualmente en la BD algunos mensajes de algún usuario (o enviar mensajes en distintas ubicaciones) y decirnos en el Readme que corrijamos con ese para que se vean varios puntos en el mapa.
