### ISSUE TITLE
Solución Ayudantía

### ISSUE THREAD

**Issue by RobinCuevas** [IIC2413/Syllabus-2019-1#156]
Hola!

Es posible que suban la solución de la ayudantía? al menos la pregunta 1 y 2 se realizaron en el computador y se comentó en la ayudantía que se iba a hacer el intento por subirla!
Sería muy útil!

Muchas gracias!

**Comment by tacorrea** [comment]
Sería muy útil para el estudio del examen tener esta solución

**Comment by jpgonzalez4** [comment]
Sería espectacular que subieran los códigos de las preguntas.

**Comment by Mahund** [comment]
Nos ayudaría muchísimo!

**Comment by TamaraCucumides** [comment]
Está arriba la solución de la P1 y P2 !!

Ánimo con el estudio!!
