### ISSUE TITLE
Muerte de Heroku y mal funcionamiento Local

### ISSUE THREAD

**Issue by Mahund** [IIC2413/Syllabus-2019-1#157]
Hola! 

Estaba arreglando algo de frontend del php cuando decidi probar una request a mi api de heroku y me di cuenta que habia dejado de funcionar, y que para cada ruta que le tengo definida se cae por "Request timeout".

Levante la api de forma local y ahora todas mis request en vez de salir bien (con beautify creo  que era que salian con colores y ordenadas) ahora salen todas de golpe.

¿Será algun problema con el servidor de Mongo que nos pasaron?

edit: Descubri que si funciona para respuestas de 1 o 2 elemenos, pero para consultas mayores muere (antes funcionaban).

**Comment by gatochico** [comment]
Me está ocurriendo lo mismo :s Las consultas de TS en la api remota me tiran timeout mientras que si corro el mismo archivo local si funcionan correctamente. Y las consultas menores si me entregan respuesta en la api...
