### ISSUE TITLE
Error Actividad1: SQL

### ISSUE THREAD

**Issue by fjtobar** [IIC2413/Syllabus-2019-1#16]
Hola, estoy finalizando la actividad de SQL y el código del final tira syntax error pero no he tocado nada de ese código porque venía así. Qué puede ser?

![Captura de Pantalla 2019-03-31 a la(s) 1 03 17 p  m](https://user-images.githubusercontent.com/42159875/55291549-113eea80-53b6-11e9-9bfa-25877fbd9dec.png)

**Comment by nivek0o0** [comment]
Hola,
según la documentación de SQLite, no se deben poner paréntesis.
Corregiremos esto a la brevedad.

**Comment by fjtobar** [comment]
Gracias ahi me funcionó! ojo que hay que cambiar "Rating" por "crating"
