### ISSUE TITLE
Ayudantia PHP "Ejecutar" los archivos

### ISSUE THREAD

**Issue by aamedinaj** [IIC2413/Syllabus-2019-1#17]
Buenas, queriendo practicar cómo se verían las PHP-HTML-cosas en el navegador, meti toda la carpeta AyudantiaPHP en el Sites de mi grupo (usando filezilla), y luego me estanqué porque no sé cómo "ejecutar" los archivos, o abrirlos. ¿Cómo se hace?

**Comment by valerojasm** [comment]
Hola!

Si accedes a `bases.ing.puc.cl/~grupoXX/AyudantiaPHP/nombre_archivo.php`
desde tu navegador con XX tu número de grupo vas a poder ver todos los
archivos que subas a esa carpeta. Cualquier archivo/carpeta que metas en
`Sites` la vas a poder acceder de esa forma.

Saludos!

*Valentina Rojas Mercier*
Estudiante de Ingeniería Civil // DCC UC
Pontificia Universidad Católica de Chile

**Comment by valerojasm** [comment]
Hola!

Si accedes a `bases.ing.puc.cl/~grupoXX/AyudantiaPHP/nombre_archivo.php` desde tu navegador con XX tu número de grupo vas a poder ver todos los archivos que subas a esa carpeta. Cualquier archivo/carpeta que metas en `Sites` la vas a poder acceder de esa forma.

Saludos!
