### ISSUE TITLE
AyudantiaPHP >consultas> referencia a ejercicio_ayudantia

### ISSUE THREAD

**Issue by aamedinaj** [IIC2413/Syllabus-2019-1#18]
Aunque la verdad no estoy seguro si ese el verdadero problema, cuando hago alguna consulta dados los PHP de la ayudantía, me aparece un error cada vez que intento acceder a la base de datos, lo que me hace querer preguntar (después de buscar en los archivos) ¿donde se hace la referencia a "ejercicio_ayudantia.csv?", o es algo que uno mismo debe hacer? help

**Comment by cmp831** [comment]
Hola, por temas de seguridad, no se subió la configuración con la contraseña a la base de datos del servidor de la ayudantia. Esto se encuentra en `app/config/data.php`. Si quieres probar el código, puedes ingresar a `http://bases.ing.puc.cl/~ayudantia/AyudantiaPHP/`, tiene el mismo código PHP de los archivos subidos, y sí está conectado a la base de datos.

**Comment by aamedinaj** [comment]
Pasa que,, aunque puedo acceder al servidor con mis credenciales, no me carga la base de datos, o al menos no me deja a los datos. Quiero saber cómo le hago para conectar la bd 😢

**Comment by nivek0o0** [comment]
Hola, 
la referencia que se hace en las consultas corresponde a la tabla **ejercicio_ayudantia**, que está creada y poblada en nuestra Base de Datos de Postgres (usuario: ayudantia). 
Sus bases de datos de postgres (usuario: grupoXX) están vacías, por lo tanto las consultas van a fallar. Por esta razón subimos el csv, para que creen e importen los datos y puedan probar las consultas. 

Para conectarte a tu BD no olvides modificar las credenciales en el archivo data.php. Ten en cuenta que `$DBpassword` debe ser la contraseña de su base de datos de postgres. Si no la han cambiado debería ser `grupoXX`
