### ISSUE TITLE
Duda clases E/R

### ISSUE THREAD

**Issue by cacoos** [IIC2413/Syllabus-2019-1#19]
Hola!

![image](https://user-images.githubusercontent.com/30879716/55357574-b1bf0880-54a3-11e9-9578-13b50101db15.png)

Aquí estamos asumiendo que una fila de la tabla "arriendo" será solo una transacción y que esta no puede tener más de una película? Me complica ver las flechas como las relaciones 1:N cuando tenemos 4 entidades.

Gracias!

**Comment by alanezz** [comment]
Hola,

Esto en general no se ve en la vida, pero la idea es la siguiente:

En la tabla arriendo, cada combinación de (id boleta, id local, id película) puede ir acompañado por a lo más por un único id de persona. De la misma forma, cada combinación de (id boleta, id local, id persona) puede ir acompañado a lo más por un único id película.

A eso nos referimos cuando se dice que boleta, local y película determinan la persona y que boleta, local y persona determinan la película.

Ojo! el ejemplo está lejos de ser una buena modelación, pero es para enseñar cómo se leen los diagramas ER cuando hay flechas y están involucradas más de dos relaciones.

Saludos.

**Comment by cacoos** [comment]
Muchas gracias!!
