### ISSUE TITLE
Tutorial Servidor

### ISSUE THREAD

**Issue by felipesilvadv** [IIC2413/Syllabus-2019-1#2]
## Conexión con el servidor
Para conectarse al servidor pueden seguir el tutorial disponible en la carpeta Proyecto de este repositorio.

## Cambio de clave del Usuario
Una vez que ingresen al servidor, deberían cambiar su contraseña para evitar el ingreso de usuarios malintencionados. Para ello deben utilizar:
```bash
passwd
```
Este comando les pedirá su clave actual y su clave nueva dos veces. Si es su primera vez usando una consola, no se asusten si al escribir no les salen asteriscos para la contraseña, eso es normal. 

## Ingresar al DBMS Postgres
Una vez dentro del servidor, pueden ejecutar el siguiente comando para ingresar a su base de datos:
```bash
psql
```
Se les pedirá una contraseña, que en principio es la misma que utilizaron para ingresar al servidor por primera vez ('grupoXX'). Se sugiere que también la cambien para evitar accesos no autorizados. 

## Cambio de clave Postgres
Una vez dentro de la terminal de postgres, pueden ejecutar:
``` SQL
ALTER USER <grupoXX> ENCRYPTED PASSWORD 'newpassword';
```
Debería mostrarles el siguiente output
``` SQL
ALTER ROLE
```
Con eso esta listo el cambio de clave.

## Sintaxis en Postgres
Existen 2 tipos de comandos: 
- los que son propios del DBMS y sirven para administrar el sistema. Estos comienzan con ' \ ' y no terminan con ' ; '. Por ejemplo: ```\dt```
- los que son típicos de SQL y que sirven para administrar las tablas. Estos deben terminar con ' ; ' Por ejemplo: ```SELECT * FROM Tabla;```

## Importar datos en Postgres
Para ello pueden utilizar el siguiente comando
``` SQL
\COPY nombre_tabla from 'relative/path/to/file.csv' DELIMITER ',' CSV HEADER
```
Aquí es importante destacar un par de cosas:

- La ruta relativa comienza desde su carpeta de usuario, es decir, si los datos están en el servidor en `'/home/grupoXX/entrega1/CSV/datos.csv'`, en el comando de postgres deberían escribir `'/entrega1/CSV/datos.csv'`
- **DELIMITER** sirve para indicar el caracter de separación de los datos.
- **HEADER** indica la presencia de una fila de encabezado, para ignorarla al importar los datos.
- Las columnas de datos se insertan de forma ordenada y correlativa en la tabla. Si desean insertar con un orden personalizado, pueden utilizar:
``` SQL
\COPY nombre_tabla(atributo2, atributo1, atributo3) from 'relative/path/to/file.csv' DELIMITER ',' CSV HEADER
```

## Subir archivos del proyecto al servidor (Entregas 1 a 5)

**OJO: Deben coordinarse con su compañero de grupo para no subir archivos al mismo tiempo y sobrescribirse mutuamente.**

Aquí explicaré dos formas de subir y bajar los archivos desde y hacia el servidor, una es sencilla, usando una interfaz gráfica como FileZilla y otra un poco más compleja, con el comando `scp`, para quienes prefieren usar la terminal UNIX/PUTTY. Ustedes pueden elegir cual usar, bajo su responsabilidad, son formas distintas de hacer lo mismo.

### Vía FileZilla (Fácil)
![Captura de pantalla de 2019-03-19 20-22-26](https://user-images.githubusercontent.com/26146850/54648561-81c83c00-4a85-11e9-8e78-d2c2bc8a125d.png)

Esta es la interfaz de Filezilla luego de la descarga e instalación. El sector izquierdo corresponde a los directorios y archivos en su computador, mientras que el lado derecho corresponderá al servidor. 

En la parte superior hay entradas para servidor, usuario, contraseña y puerto. Deben rellenarlas con los siguientes datos para conectarse:
```
servidor: bases.ing.puc.cl
user: grupoXX
password: mypassword
port: 22
```
También existe la posibilidad de guardar esta conexión para luego ingresar con 1 click y no tener que escribir las credenciales cada vez. Se sugiere investigar.

![Captura de pantalla de 2019-03-19 20-23-05](https://user-images.githubusercontent.com/26146850/54648694-fd29ed80-4a85-11e9-988b-4663e5585421.png)

La transferencia de archivos es bidireccional y para ello pueden arrastrar los archivos o hacerles doble click. También es posible mover, renombrar o eliminar archivos y carpetas en el servidor. 

![Captura de pantalla de 2019-03-19 20-24-20](https://user-images.githubusercontent.com/26146850/54648845-87725180-4a86-11e9-9475-8c9f85129baa.png)

Una vez que terminen y quieran desconectarse, solo tienen que apretar el botón que se resalta en la última imagen (en la parte superior).

### Vía Terminal con el comando SCP (Díficil)
Los usuarios de Windows pueden ocupar el comando `pscp` en lugar de `scp,` el que se instala automáticamente junto con Putty.

En los demás sistemas operativos los archivos y carpetas se pueden copiar desde y hacia el servidor utilizando la siguiente sintaxis:
```bash
scp   ruta_y_archivo_a_transferir    ruta_destino
```
o bien
```bash
scp  -r  ruta_y_carpeta_a_transferir    ruta_destino
```

Para especificar rutas en el servidor debemos anteceder `grupoXX@bases.ing.puc.cl:`. Las rutas del servidor comienzan con `/home/grupoXX/....`. Podemos abreviar estas dos carpetas con `~`.
Así, podríamos utilizar este comando de las siguientes formas:

Archivo hacia el servidor:
```bash
scp  /IIC2413/Proyecto/Entrega1/Informe.pdf  grupoXX@bases.ing.puc.cl:/home/grupoXX/Sites/Entrega1/
```
Archivo desde el servidor:
```bash
scp  grupoXX@bases.ing.puc.cl:~/Sites/Entrega1/index.php  .
```
Carpeta hacia el servidor:
```bash
scp  -r  /IIC2413/Proyecto/Entrega1  grupoXX@bases.ing.puc.cl:~/Sites/
```
Carpeta desde el servidor:
```bash
scp  -r  grupoXX@bases.ing.puc.cl:~/Sites/Entrega1/  .
```

- La opción `-r` le indica al comando que transfiera recursivamente lo que existe dentro de la carpeta
- El `.` significa que el destino es el directorio actual.
- `~` es un abreviación de `/home/GrupoXX`
- el comando `ls` sirve para listar el directorio actual

## Organización del servidor y URL

* Sus próximas entregas consisten en presentar consultas en un sitio web, y luego ir añadiendo funcionalidades. Se ingresará a las consultas desde la dirección http://bases.ing.puc.cl/~grupoXX/. Esta ruta mostrará todo lo que tengan dentro de la carpeta **Sites**.
* Se recomienda que cada una de las entregas se suban de forma separada dentro de la carpeta `Sites`, es decir, que creen una carpeta llamada `entregaX` para subir los archivos correspondientes a ella. Esto para hacer posible las recorrecciones. De esta forma, si suben un `archivo.php` en `/grupoXX/Sites/entregaX/`, podrán visualizarlo en la siguiente dirección: http://bases.ing.puc.cl/~grupoXX/entregaX/archivo.php

**Comment by mvcavieres** [comment]
Hola, tengo un problema en el cambio de clave de usuarios, al intentar cambiarla, me tira el siguiente error: 
> grupo11 is not in the sudoers file.  This incident will be reported.

**Comment by cmp831** [comment]
@mvcavieres Hubo un error en el tutorial, para cambiar la contraseña de tu usuario actual no se requiere usar sudo. Intentalo solo usando `passwd`.

**Comment by raespinoza4** [comment]
Hola, tuve problemas al momento de pasar los datos en csv a las tablas en postgres.

En el tutorial dice :

> _La ruta relativa comienza desde su carpeta de usuario, es decir, si los datos están en el servidor en '/home/grupoXX/entrega1/CSV/datos.csv', en el comando de postgres deberían escribir '/entrega1/CSV/datos.csv'_

Pero me decía que el archivo no existe, al contrario de lo escrito ahí me funciono correctamente con la ruta '/home/grupoXX/entrega1/CSV/datos.csv'

No se si fue un error puntual pero lo escribo por si le pasa a alguien mas.
