### ISSUE TITLE
Consultas sobre la guía de la Interrogación 1

### ISSUE THREAD

**Issue by arpincheira** [IIC2413/Syllabus-2019-1#24]
Hola, me encontraba resolviendo la guía de la interrogación 1 y me surgieron dos dudas con respecto a la pregunta 1. La primera de estas es con respecto a la primera consulta que nos piden realizar la que dice lo siguiente: "El nombre de cada banda junto al nombre de cada integrante." De esta consulta logré obtener 2 interpretaciones, la primera es que piden simplemente hace un par de _joins_, y la otra es bastante más compleja, ya que se entiende como que nos están solicitando responder los integrantes de cada banda, por cada banda y sin tener información alguna a los nombres de las bandas. ¿Cuál de estas interpretaciones sería la correcta?

La segunda duda es con respecto a la tercera consulta de la misma pregunta, en la que nos piden las bandas enemigas durante el 2012, aquí mi interrogante sería la siguiente: ¿Nos piden una respuesta que muestre los nombres o las id de las bandas que eran enemigas entre ellas o todas las bandas que tenían un enemigo durante ese año(retornando solo una id o un nombre en este caso)?

Muchas gracias de antemano.

**Comment by alanezz** [comment]
Hola,

Respecto a la primera pregunta, la primera interpretación es la correcta. Respecto a la segunda pregunta, se piden todas las bandas que tenían un enemigo (la respuesta es una relación unaria).

Saludos!
