### ISSUE TITLE
Pregunta 5 y 7 parte sql ayudantía 2.

### ISSUE THREAD

**Issue by chocopiano** [IIC2413/Syllabus-2019-1#25]
Hola, alguien me podría explicar porfa la solución de dicha pregunta. La respuesta de ayudantía fue 
```pgsql
SELECT uid FROM Partidas P1
where NOT EXISTS
(SELECT * FROM PartidasP2
WHERE P1.uid=P2.uid
AND P2.duracion>30) 
```

Y la 7 que hay unas cosas raras jajaja

Gracias!

**Comment by arpincheira** [comment]
Hola, no soy ayudante, pero creo que lo que hace la consulta de la ayudantía es crear una tabla que no considere ninguno de los datos presentes en el exists, es decir, si existe un dato en P1(partidas) que posea la misma id que un dato en P2(también la tabla partidas) y que tenga una duración mayor a 30 entonces no lo considera.

Con respecto a la consulta 7, no la solucionaron en mi ayudantía pero  no se si sirva la siguiente solución: 
SELECT Alias 
FROM Users, Partidas
WHERE Users.uid = Partidas.uid and Partidas.duracion = (SELECT MAX(duración) FROM Partidas)

Puede que no sirva mucho pero espero haberte ayudado

**Comment by TamaraCucumides** [comment]
Hola, lo que comenta @arpincheira está bien.

El comando **EXISTS** lo que hace es retornar TRUE si la consulta anidada es no vacía y retornar FALSE en caso de que sea vacía. Lo que hace la solución entonces es seleccionar a aquellos usuarios que no posean ninguna partida cuya duración sea mayor a 30 minutos.

Para la pregunta 7 si está medio extraña la solución, invoco a @cmgainza para que la revise/explique. De todas maneras, la consulta que propone @arpincheira está buena!

**Comment by TamaraCucumides** [comment]
Pueden considerar esta solución también para la consulta 7:

```python
SELECT U.alias
FROM Usuarios AS U, Partidas AS P1
WHERE U.uid = P1.uid AND
NOT EXISTS (SELECT * FROM PARTIDAS AS P2
WHERE P2.duración > P1.duración)
```

**Comment by TamaraCucumides** [comment]
Y la consulta de la 7 corregida queda de la siguiente manera:

```python
SELECT U.alias
FROM Usuarios AS U, Partidas AS P1
WHERE U.uid = P1.uid AND
0 = (SELECT COUNT(*)
FROM PARTIDAS AS P2
WHERE P2.duración > P1.duración)
```

**Comment by gnacrur** [comment]
Hola  @TamaraCucumides  , quería saber si lo siguiente estaría bien:
SELECT U.alias
FROM Usuarios AS U, Partidas AS P1
WHERE U.uid = P1.uid AND P.duracion > ALL (SELECT P2.duracion FROM PARTIDAS AS P2)

**Comment by chocopiano** [comment]
En la 5 es valido poner:
SELECT U.alias FROM Partidas P1
EXCEPT
SELECT U1.alias FROM Partidas P2
WHERE P2.duracion>30

??

**Comment by TamaraCucumides** [comment]
Ojo que la tabla Partidas no posee los alias.

**Comment by chocopiano** [comment]
suponiendo que me pedían el uid en vez del alias, estaba bien lo anterior o no?
