### ISSUE TITLE
I1-2018-2 Pregunta 1 Álgebra relacional

### ISSUE THREAD

**Issue by arpincheira** [IIC2413/Syllabus-2019-1#26]
Hola, tengo una duda con respecto al uso de álgebra relacional para poder obtener el resultado de la primera consulta solicitada donde piden explícitamente las aerolínias que tengan vuelos directos a TODAS las ciudades de estados unidos.

El problema viene principalmente en la parte de TODAS, pues no se me ocurre si existe un modo de verificar eso solamente sabiendo el dato del país al que corresponden con álgebra relacional

Muchas gracias de antemano

**Comment by alanezz** [comment]
Puedes asumir que son todas las ciudades que están en la tabla `Ciudad` donde el país sea Estados Unidos.

Saludos.

**Comment by chocopiano** [comment]
Entonces se refiere a las aerolineas que llegan a alguna de las ciudades de estados unidos o no? Porque a mí tampoco se me ocurre como hacerlo con algebra relacional.

**Comment by alanezz** [comment]
No, no algunas, deben llegar a todas. Hicimos algo parecido en clases cuando preguntábamos por los capitanes que habían reservado todos los botes.

Saludos.

**Comment by arpincheira** [comment]
@chocopiano mira la slide 20 del ppt 5, ahí puede que veas a lo que se refiere @alanezz 

P.D.: Muchas gracias por la ayuda
