### ISSUE TITLE
Duda Guia I1

### ISSUE THREAD

**Issue by bgsamilla** [IIC2413/Syllabus-2019-1#27]
En la pregunta de álgebra relacional, cuarta consulta, se nos pide crear un operador "enemigos" que recibe una relación binaria y un año.
Ahora mi duda es si la relación que recibe es binaria, según entiendo tiene 2 columnas, que yo asumo serán los ids de las bandas que colaboran. Entonces ¿como relaciono el año con la tabla?.
¿Esta tiene de igual forma una columna del atributo fecha?
¿Estoy confundiendo conceptos?

Saludos!

**Comment by alanezz** [comment]
Perdón, es un typo. Debería decir "recibe una relación como colabora". Es decir tienes los dos ids y la fecha.

Saludos.
