### ISSUE TITLE
GROUP BY

### ISSUE THREAD

**Issue by bgsamilla** [IIC2413/Syllabus-2019-1#28]
¿Se pueden hacer sub-grupos dentro de un grupo?

Digamos que tengo la siguiente tabla:
FRUTAS(fruta, color, cantidad, dueño)
Y la instancia tiene manzanas rojas y verdes, y peras naranjas y azules (por alguna extraña razón)
Si quisiera agrupar por fruta, entonces tendría 2 grupos manzanas y peras.
Pero si estos grupos los quisiera subdividir por color ....
¿Se puede hacer?
¿Como seria la sintaxis en SQL?

Lo que me interesa en este caso seria saber la cantidad de una fruta según el color

**Comment by TamaraCucumides** [comment]
Holaa, 

en ese caso dentro del GROUP BY deberías poner ambos atributos, es decir:

**GROUP BY fruta, color**

Esto lo que hace es agrupar aquellos elementos que tengan igual valor en el atributo fruta y en el atributo color.

Puedes revisar el siguiente link si te quedan dudas: https://stackoverflow.com/questions/2421388/using-group-by-on-multiple-columns
