### ISSUE TITLE
Cliente SSH en Windows

### ISSUE THREAD

**Issue by Mahund** [IIC2413/Syllabus-2019-1#3]
Segun el tutorial de SQLite para Linux basta el terminal pero para Windows se recomienda utilizar putty.

Mi consulta: no se puede ocupar git bash que esta basado en Linux?

Al menos logre ingresar al servidor del proyecto sin problemas pero no se si a futuro tenga algún conflicto, gracias.

**Comment by cmp831** [comment]
Hola, si se puede, no debe existir problemas de compatibilidad.
Si te resulta más fácil, también puedes tratar de usar SSH directamente en powershell. No está incluido en el tutorial, porque no viene preinstalado en todas las versiones de Windows,  y la instalación no es un proceso trivial.
