### ISSUE TITLE
Duda Guía 1, consulta 3 Algebra relacional

### ISSUE THREAD

**Issue by chocopiano** [IIC2413/Syllabus-2019-1#30]
Porfa alguien me puede orientar de como se hace. Gracias

**Comment by alanezz** [comment]
La idea es más o menos así:

Haces el producto cruz de colabora consigo mismo (seleccionando sólo las tuplas del 2012), entonces te fijas que el bid1 de la izquierda sea distinto al de la derecha y que los bid2 sean iguales. Con esto están obteniendo para pares de bandas distintas las bandas que tocaron en común. Por lo mismo esas bandas no son enemigas. Luego puedes restarle a todas las bandas las que no son enemigas.

Saludos.
