### ISSUE TITLE
Modelación E/R

### ISSUE THREAD

**Issue by Franco1605** [IIC2413/Syllabus-2019-1#32]
Hola !
cuando en los ejercicios tengo que pasar de la modelación al esquema, ¿tengo que hacer una tabla por cada entidad y relación presente?¿ o solo de las relaciones ?

Gracias de antemano !

**Comment by alanezz** [comment]
Hola,

Recuerda que el esquema es la declaración de TODAS las tablas de tu base de datos, incluyendo las relaciones.

Saludos.

**Comment by Franco1605** [comment]
Ok. Gracias
