### ISSUE TITLE
Guía I1 Consulta 5

### ISSUE THREAD

**Issue by RobinCuevas** [IIC2413/Syllabus-2019-1#33]
Alguien me puede ayudar con la consulta para saber los equipos con más de un 75% de partidos ganados de local? Muchas gracias!!

**Comment by chocopiano** [comment]
x2

**Comment by alanezz** [comment]
La idea es más o menos esta:

Primero hay que contar los goles:

```SQL
SELECT id_partido, eid_favor, COUNT(*)
FROM Gol
GROUP BY id_partido, eid_favor
```

Luego le haces join a esa tabla con la de partidos dos veces. Siempre tienes que hacer calzar el id del partido, pero una vez tienes que hacer calzar el eid_favor con el equipo local, y otra vez con el id visita. Al final te quedará una tabla `Partido` extendida con los goles del local y los goles de la visita.
Tienes que tomar esa tabla extendida y generas dos consultas:

1. Contar para cada equipo de local el número de tuplas donde sus goles sean mayor que los del rival.
2. Contar para cada equipo local el número de partidos.

Luego haces join por el id del local de ambos resultados. Aquí haces la división de partidos ganados en partidos totales, le das un alias y te aseguras que ese atributo sea mayor a 0.75.

Saludos.
