### ISSUE TITLE
Entrega 2 - Poblar tablas

### ISSUE THREAD

**Issue by jncaceres** [IIC2413/Syllabus-2019-1#35]
Hola, para la entrega 2, debemos utilizar las tablas como nos la dieron a nosotros en los csv? o debemos dejar las tablas como las modelamos en nuestro diagrama y modelo?
Si es que el caso es el segundo, se pueden modificar las tablas desde excel o hay que cargar las tablas con codigo e ir seleccionando cuales columnas queremos en cada tabla?

**Comment by alanezz** [comment]
Hola,

Para la entrega deben tener las tablas en el servidor como ustedes las modelaron. Para poblar las tablas pueden procesar los csv que les dimos con Python o cualquier otra forma, generando un csv para cada una de sus tablas. Lo importante es que las tablas pobladas sean consistentes con los datos que les entregamos.

Saludos.
