### ISSUE TITLE
Datos csv Entrega 2

### ISSUE THREAD

**Issue by chocopiano** [IIC2413/Syllabus-2019-1#37]
Viendo los excel, se puede notar que los atributos estan separados por coma. En el excel de hoteles_habitaciones las direcciones aparecen entre comilla lo que permite validar todo lo que esta dentro de esta como un atributo (incluyendo las comas) pero resulta que hay casos como en el hotel Saldivar (desde la línea 152) que las direcciones no aparecen con comillas y al separarlos me divide la direccion en mas atributo con lo cual se agrega un columna extra que no debería existir. Mi pregunta es: Es parte del trabajo nuestro arreglarlo o es un error que lo van a arreglar? Gracias!

**Comment by naquiroz** [comment]
Hola :wave: !
No es un error :thinking: , las celdas que contengan un dato con coma, vendrán con comillas, y las que no, no tendrán,  Por lo tanto, deberías poder trabajar los datos tal como están.
Saludos! :wave:

**Comment by chocopiano** [comment]
<img width="1211" alt="Captura de Pantalla 2019-04-12 a la(s) 10 03 13" src="https://user-images.githubusercontent.com/37153534/56042955-3d3d6280-5d0a-11e9-86a1-155d784ef786.png">
 En ese caso que pasaría? La dirección no esta con con comillas por ende se esta agregando un atributo extra a los datos. Yo lo arregle, pero me demore demaciado en hacerlo y ahora que subieron este nuevo archivos, me di cuenta que los datos no son iguales y debo hacerlo todo de nuevo.

**Comment by chocopiano** [comment]
Existe la opcion de ajustar el rid a la tabla que yo cree? Porque no quiero tener que arreglar todo nuevamente. Saludos!

**Comment by naquiroz** [comment]
@chocopiano te recomiendo abrir el archivo como texto plano, no con excel dado que la forma en que se abre depende del idioma del computador, el `LOCALE` y el programa mismo con el cual se abre (excel, libreoffice, google sheets, etc).
Respecto a ese caso, me podrías enviar la línea en la que está para verificar si está bien?

Respecto a el `rid`, no entendi tu pregunta. Si la pregunta es si podemos cambiar la columna en los archivos, no es posible. Si tu pregunta es si puedes colocar la columna `rid` en tu tabla de tu base de datos, si, puedes hacerlo, tienes completa libertad de colocar las columnas en el orden que quieras (asumiendo que esas columnas corresponden a esa tabla).

**Comment by chocopiano** [comment]
A partir de la 452 (Hotel Corporacin Adame), tambien desde la 752 y varios más para abajo.

**Comment by naquiroz** [comment]
Si observas:
![image](https://user-images.githubusercontent.com/29825816/56049692-0a9a6680-5d18-11e9-8342-db99d2d1b5a0.png)
La línea 452 (y todas las similares) tienen la primera columna con comillas, por lo que la coma está dentro de la primera columna. En la 752 ocurre lo mismo.

A fin de cuentas, debes considerar que las filas que tengan comas dentro de comillas, debe consideras esa coma dentro de la misma columna :+1:

**Comment by chocopiano** [comment]
Perfect, ahora puedo ver que era gracias a excel el porque no se veían esas comillas. Mi duda ahora es, como puedo arreglarlo para que se vean esas comillas en excel para no tener que trabajar en un texto plano?

**Comment by naquiroz** [comment]
Personalmente, no se :sweat_smile: . Pero hay extensiones en varios editores de código para ver los csv como tablas. Sino, podrías googlearlo :smile:

**Comment by chocopiano** [comment]
Por si a alguien le sirve, así lo arregle:
https://www.geeknetic.es/Noticia/11610/Trucos-Como-abrir-correctamente-un-archivo-CSV-en-Excel.html

**Comment by valerojasm** [comment]
De todas formas, es preferible que no lo abras en excel, a veces puede desconfigurar los delimiters y sería una lata si no te das cuenta. En general, los csv los lees en editores de texto, y como dice @naquiroz existen varios packages que puedes instalar si te acomoda más leerlos como tablas. Saludos!

**Comment by gnacrur** [comment]
@valerojasm ¿ A que te refieres con desconfigurar los delimiters? Quería trabajar en excel para crear las tablas que nos faltan con buscarv y las facilidades que entrega excel por eso pregunto.

**Comment by naquiroz** [comment]
@gnacrur se refiere a que _excel_ puede cambiarte los separadores, o como están ordenados, al abrir el archivo y luego guardarlo.
