### ISSUE TITLE
Datos entregados - Entrega 2

### ISSUE THREAD

**Issue by RobinCuevas** [IIC2413/Syllabus-2019-1#38]
Hola! 
Tengo una duda en los datos entregados, se me es imposible relacionar cada hotel con una región y necesito saber esto para responder las consultas!
Gracias!

**Comment by RobinCuevas** [comment]
(grupo impar)

**Comment by chocopiano** [comment]
x2

**Comment by nivek0o0** [comment]
Hola,
el archivo **restaurant_platos.csv** trae el id de la región

**Comment by naquiroz** [comment]
Hola! Era un error, efectivamente faltaba la columna, ahi lo subimos correctamente! :tada: 

Saludos! :wave:
