### ISSUE TITLE
Duda consultas

### ISSUE THREAD

**Issue by jncaceres** [IIC2413/Syllabus-2019-1#4]
Para realizar consultas en el curso ¿se puede utilizar el simbolo  γ para hacer un GROUP BY en algebra relacional? ¿o como no lo pasamos no se puede utilizar?

**Comment by alanezz** [comment]
Hola,

En el curso nos limitamos al álgebra relacional de proyección, selección, producto cruz y operadores de conjuntos. No vamos a trabajar con GROUP BY en el álgebra relacional, solo en SQL.
En las consultas que te pediremos hacer en álgebra relacional no vas a poder usar γ, aunque en general no debiese ser necesario.

Saludos!
