### ISSUE TITLE
BCNF 

### ISSUE THREAD

**Issue by csolguin** [IIC2413/Syllabus-2019-1#40]
Con respecto a la entrega 2 del proyecto, ¿Qué debe cumplir el BCNF y cómo debemos justificarlo?
De antemano gracias

**Comment by valerojasm** [comment]
Hola! Tal como dice el enunciado, todo tu modelo (todas las tablas) debe estar en BCNF, y para justificar que esto se cumple les pedimos que lo hagan mediante dependencias funcionales en el PDF que deben entregar.

Avísame si igual te quedan dudas.
Saludos!

**Comment by julioag** [comment]
Hola, tengo una duda con el formato de BCNF y es que si puede tener una tabla con 2 columnas y que la llave sea la tupla de estos 2 valores? Revisé el pdf de la clase dependencias y no me quedó claro.

Gracias de antemano.
