### ISSUE TITLE
Falta de información para una base de datos "coherente"

### ISSUE THREAD

**Issue by Faalfaro** [IIC2413/Syllabus-2019-1#41]
Hola, quería saber que pasa con las tablas que relacionan al usuario con los platos y los tours, ya que solo entregaron la tabla reserva que relaciona los usuarios con las habitaciones. Mi pregunta es si en el modelo E/R ¿Relaciono a usuarios con platos (por ejemplo con "pide") y usuarios con tours (por ejemplo con "contrata") o simplemente pongo a usuarios solo relacionadose con habitaciones (con "reserva") ?. La misma pregunta es para crear la base de datos en SQL, ¿Creo las tablas que relacionan a usuarios con platos y tours, dejándolas vacías, o simplemente no las creo?.
Gracias de antemano!

**Comment by valerojasm** [comment]
Hola!
Al menos para esta entrega, no veo que haya la necesidad (ni tampoco tienes la información necesaria) para crear esas tablas. Las consultas que deben realizar no piden ninguna de las asociaciones que nombras, por lo que la modelación no va por ahí. Si te fijas, por ahora las acciones del usuario se reducen solamente a reservar habitaciones.

Espero que te sirva,
Saludos!
