### ISSUE TITLE
ERROR:  invalid byte sequence for encoding "UTF8": 0xdc 0xcd

### ISSUE THREAD

**Issue by chocopiano** [IIC2413/Syllabus-2019-1#43]
Me sale este error al crear las tablas, he googleado pero no lo he podido solucionar...alguien sabe que puedo hacer?

**Comment by chocopiano** [comment]
solucionado

**Comment by valerojasm** [comment]
Recuerda cerrar tus issues cuando lo soluciones, saludos!
