### ISSUE TITLE
[PHP] - Error al consultar a la base de datos

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2413/Syllabus-2019-1#44]
Hola, al intentar conectarme a la base de datos, me arroja este error:

![image](https://user-images.githubusercontent.com/37163344/56099327-97405280-5ed9-11e9-9adf-cf9a17593120.png)

Un `Screenshot` de lo que tengo:

![image](https://user-images.githubusercontent.com/37163344/56099319-63fdc380-5ed9-11e9-9420-69fa7b85be3c.png)

Saludos!

**Comment by cmp831** [comment]
tl;dr:  Cambiar `%DBport` a `5432`
Revisando el error que te arroja PHP, debe ser relacionado con el protocolo que estas usando para conectarte a Postgres. Puesto que estás ejecutando tu código dentro del servidor, no debes connectarte usando SSH. Además, estas tratando de conectarte a Postgres, no hacer una conección SSH, por lo que debes cambiar tu `%DBport` definido en `data.php` con el puerto 5432, cual es el puerto de Postgres.

**Comment by VicenteVicente** [comment]
Gracias!! 😃

**Comment by VicenteVicente** [comment]
Disculpa, cambié el `$DBport` a `5432` y me arroja la siguiente excepción:

`'PDOException' with message 'SQLSTATE[08006] [7] could not connect to server: Connection refused Is the server running on host "bases.ing.puc.cl" (146.155.13.141) and accepting TCP/IP connections on port 5432?'`

Saludos!

**Comment by cmp831** [comment]
Verdad, no he visto lo que tienes puesto en $dbhost, cámbialo a 'localhost' y te debería funcionar.

**Comment by VicenteVicente** [comment]
Ahora si que sí! GRACIAS!!

**Comment by agustinespildora** [comment]
Como se puede abrir el archivo y correrlo en el servidor? Se puede hacer directamente en filezilla? o hay que ingresar algún comando en la terminal?

**Comment by valerojasm** [comment]
Hola!
 
Echale una mirada al tutorial que subimos a la wiki.

**Comment by agustinespildora** [comment]
Gracias! @valerojasm . No lo había visto
