### ISSUE TITLE
Tour en regiones y agencias

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2413/Syllabus-2019-1#45]
Los Tour pueden estar mas de una vez por agencia pensando que pueden estar en 2 regiones de una agencia? y tambien pueden estar mas de una vez en una region pensando que dos agencias deistintas lo ofrecen en una region?

**Comment by naquiroz** [comment]
Hola! Creo que no entendí muy bien tu pregunta, intentaré responderla de igual manera.

**Los tours son por agencia.** Un agencia **puede** estár en más de una región, por lo que pueden haber tours de la misma agencia, en distinas regiones. Lo que **no puede ocurrir,** es que esté el mismo tour dos veces en una misma región, ni para dos agencias distintas.
