### ISSUE TITLE
Datos Entrega 2 Grupo impar

### ISSUE THREAD

**Issue by javalenzuela3** [IIC2413/Syllabus-2019-1#46]
Viendo los datos que fueron entregados y el enunciado correspondiente a la entrega 1, notamos que no existe tipo de habitación en los datos, mientras que esto si es pedido en el modelo.
La pregunta es: asumo que esto es un error del enunciado original, o que debiera existir una columna correspondiente a los tipos de habitación en las tablas, o que la interpretación original de tipo de habitación no corresponde a nada relevante dentro del problema? (razón entonces para preguntarse por qué se colocó en primera instancia). 
Gracias.

**Comment by naquiroz** [comment]
Hola! :wave:

Puedes asumir que para esta entrega, esa información no es necesaria. Se colocó en primera instancia para que ustedes pudieran ver como se modelaba una base de datos de manera correcta.

Saludos! :wave:
