### ISSUE TITLE
Ayuda! [Entrega 2]

### ISSUE THREAD

**Issue by bgsamilla** [IIC2413/Syllabus-2019-1#47]
Hola!
Algún ayudante de proyecto que pueda coordinar juntarse conmigo o mi compañero.
Por motivos de fuerza mayor ninguno de nosotros pudo asistir a la ayudantía de PHP/Entrega 2.
Nos intentamos poner al corriente con los datos de la ayudantía y la wiki que subieron, pero no nos ha servido de mucho, y no podemos avanzar con la entrega.
Estamos bastante perdidos con lo que hay que hacer :(
Me pueden contactar a bgsamilla@uc.cl
Saludos!

**Comment by bgsamilla** [comment]
Solo pido unos minutos ...
Por Favor
T.T

**Comment by valerojasm** [comment]
Hola! Perdón por no haberte contestado antes. No te preocupes, yo te puedo ayudar mañana, aún están a tiempo pero para la próxima si tienen algún problema escríbannos altiro! Así pueden partir con más holgura. Escríbeme a varojasm@uc.cl para que coordinemos una hora :smile:

Saludos!
