### ISSUE TITLE
Grupo Par csv con menos informacion

### ISSUE THREAD

**Issue by FJavierOss** [IIC2413/Syllabus-2019-1#48]
Hola, solo queria hacer notar que para los parques nacionales en el enunciado de la entrega 1 constaba de un atributo que era el número de teléfono, pero revisando las tablas que nos entregaron no encontre esa columna en ninguna parte, por lo que finalmente quiero saber si se decidio que no se considera el telefono de ahora en adelante o simplemente fue un error. 

Saludos

**Comment by alanezz** [comment]
Hola,

Puedes omitir este atributo, o llenar con uno aleatorio si es necesario.

Saludos.

**Comment by FJavierOss** [comment]
Gracias,

Acabo de notar otra cosa, existen id de parques no asignados en la base de datos. Por ejemplo no hay ningun parque con el id 2, 9 , 52, 62 entre otros. Omitimos esto tambien?

**Comment by naquiroz** [comment]
Hola :wave:!
Puedes sumir que esos no hay parques con esos id. Saludos!
