### ISSUE TITLE
SELECT {A_1..A_n} - {A_n} Parámetros

### ISSUE THREAD

**Issue by fjtobar** [IIC2413/Syllabus-2019-1#50]
Si tengo una tabla con columnas desde la {A,B,..,Z} y quiero mostrar las columnas {A,B..,Y} 

Hay alguna forma de hacer esto con el SELECT (que no sea SELECT A,B,C..,Y)?
Por ej SELEC * -Z? Espero se entienda la pregunta 

PD: No quiero borrar la columna Z

**Comment by cmp831** [comment]
Esta función no está presente en Postgres ni en el standard de SQL. Si estás usando de manera muy frecuente una consulta dónde se excluya una columna, puedes crear una vista (Esto es para el proyecto, si lo quieres usar en una prueba pregunta primero si se puede utilizar vistas) con las columnas que quieres, y simplemente hacer `select * from view`

Otra opción que tengo en mente sería usar plpgsql, la cual van a aprender a usar en las próximas clases. Puedes agregar una lógica para que no incluya la columna que entregaste como parámetro. Es posible, pero no sé si valdría la pena jajaja.

Para los Views, puedes revisar esta [página](https://www.w3schools.com/sql/sql_view.asp).
Y esta [respuesta](https://stackoverflow.com/a/40521569) de stackoverflow para guiarte con plpgsql.
