### ISSUE TITLE
Normalización datos

### ISSUE THREAD

**Issue by gnacrur** [IIC2413/Syllabus-2019-1#51]
Hola,  no entiendo bien a que se refieren con: 

>  datos no vienen necesariamente normalizados

No se si se refieren a BCNF, o que pueden haber datos nulos entremedio, o que hay que cambiar el encoding o el formato de las fechas, o que simplemente los nombres de las columnas deben ser igual a nuestro esquema o todo junto. Gracias!

**Comment by valerojasm** [comment]
Hola! Significa que no vienen necesariamente en BCNF, tienen que hacerlo ustedes.

Saludos!
