### ISSUE TITLE
Normalización de datos

### ISSUE THREAD

**Issue by mmsaavedra1** [IIC2413/Syllabus-2019-1#52]
Para esta parte se espera que se **carguen** los datos de forma normalizada o podemos **crear** nuevos archivos .csv con la información normalizada y editada a nuestro criterio?

**Comment by valerojasm** [comment]
Hola! Sus tablas deben estar en BCNF, y para poblarlas deben usar los csv, por lo que primero ven si deben editar/editan los archivos y luego crean las tablas en su DB para cargarlos.

Saludos!

**Comment by mmsaavedra1** [comment]
Aqui es donde cae mi duda, ¿nosotros debemos subir los archivos .csv modificados a la entrega, o un archivo .db que contenga las instancias organizadas (como modelamos) para luego realizar las consultas?

Estoy un poco perdido con esa parte, ya que acabo de terminar la modelación :(

**Comment by valerojasm** [comment]
Te estás confundiendo con los archivos .db que ocuparon en la actividad
(que corresponden a una extensión con la que trabaja SQLite, no Postgres).
Acá tienen que modificar los csv si es necesario y crear las tablas para
cargarlos. Se entiende?

Me cuentas,
Saludos!
