### ISSUE TITLE
BCNF varios a uno

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2413/Syllabus-2019-1#53]
Hola! 

Cuando se tiene una relación de entidades de varios a uno, es necesario realizar la tabla de relación? Esto tomando el ejemplo en clases de que un producto es fabricado por una sola compañía, entonces se podría realizar la tabla del producto con el id de la compañía donde se fabrica ahorrándonos la tabla relación fabrica.

Esto está bien o debe hacer la tabla de relación fabrica para que esté en BCNF?

**Comment by ppotin** [comment]
Hola! 
No, no es necesario que hagas la tabla de relación en ese caso. Normalmente necesitas hacer una tabla de relación cuando dos entidades se relacionan N a N.

**Comment by ljrodriguez1** [comment]
Pero para la entrega se debe mostrar esa tabla o sin realizar esa tabla igual se esta en BCNF?

**Comment by ppotin** [comment]
@ljrodriguez1 Perdón por la demora pero no había visto esto. 
Con respecto a tu pregunta, no es necesario que muestres esa tabla para que tu modelo esté en BCNF.

Saludos
