### ISSUE TITLE
Supuestos - Entrega 2

### ISSUE THREAD

**Issue by jachavarri** [IIC2413/Syllabus-2019-1#54]
Hola! Quisiera saber si podemos suponer que un usuario tiene un solo correo, o que un parque o viña tienen un único teléfono y las atracciones una única url.

Saludos!

**Comment by naquiroz** [comment]
Hola! :wave: 
No veo porque va la pregunta :thinking: ,
Asumiendo que solo quieres saber si un `usuario` tiene un único `correo`, y no dos correos, si, tiene solo ún correo.

Lo mismo ocurre con `teléfono` en `parque` y `url` en `atracciones`

Saludos :v:

**Comment by jachavarri** [comment]
Por eso, ¿podría ocurrir que en el archivo usuario.csv aparezca lo siguiente?
```
id,nombre,correo
1,José Antonio,AAA@gmail.com
1,José Antonio,BBB@gmail.com
```

**Comment by naquiroz** [comment]
@jachavarri, no. Quizá me expliqué mal, un usuario **tiene un solo correo**, no puede exisitir el mismo usuario, con dos correos.

Saludos.

**Comment by jachavarri** [comment]
Muchas gracias!
