### ISSUE TITLE
[BCNF] - Tablas de Relaciones

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2413/Syllabus-2019-1#55]
No entiendo muy bien cómo aplicar `BCNF` a una tabla que es una relación entre dos tablas y además tiene atributos. ¿Dejar tres `Primary Key` se considera normalizado?

Saludos!

**Comment by valerojasm** [comment]
Hola! Si tienes 3 primary key de las que dependen otros atributos esa tabla no estaría en BCNF, puedes repasar la clase de dependencias funcionales para que te ayude a entenderlo mejor.

Avísame si te quedan dudas!
Saludos,

**Comment by VicenteVicente** [comment]
En este caso esta tabla relaciona a otras dos, pero ya tiene una `id` de la que dependen los atributos de la relación, además de los `id` de las otras dos tablas, por lo pareciera que es conveniente dejar una `Primary Key` y las otras dos `id` como `Foreign Key`, sin embargo, según lo que nos enseñaron en clases, cuando una tabla relaciona a otras dos las `Primary Key` de este tipo de tablas debe ser las `Primary Key` de las tablas que relaciona. Esto es lo que me genera la confusión. Espero que se entienda 😢 

Saludos!!

**Comment by VicenteVicente** [comment]
Ya lo solicionamos, gracias! 😀
