### ISSUE TITLE
consulta 4 (agencias en una sola región)

### ISSUE THREAD

**Issue by PaoloFabia** [IIC2413/Syllabus-2019-1#56]
Hola!
Cuando nos preguntan por "todos los tour de las agencias que están presente sólo en una región", se refiere a buscar las agencias que solo se encuentran en  una región, y de ellas mostrar todos sus tours? (es decir, tendríamos agencias de  distintas regiones). O se refiere a ver todas las agencias de una región dada y a partir de eso mostrar todos los tours.

Gracias!

**Comment by naquiroz** [comment]
Hola! :v:

Se refiere a la primera: 
> se refiere a buscar las agencias que solo se encuentran en una región, y de ellas mostrar todos sus tours? 

Saludos :wave:
