### ISSUE TITLE
Ver archivos subidos al servidor en bases.ing.puc.cl

### ISSUE THREAD

**Issue by gnacrur** [IIC2413/Syllabus-2019-1#57]
Hola, estoy intentando subir un archivo php a mi carpeta en el servidor (a través de filezilla) tal como nos dijieron en la ayudantía (bases.ing.puc.cl/~grupo12/entrega2/archivo.php y también probé cambiando ~ por el resto del path). El problema es que cuando voy a la dirección donde supuestamente debería poder ver el cambio hecho, me sale que la página no existe. No se si hay que ejecutar algo antes o quizás el url que debiese poner en mi navegador es otro. Gracias de antemano!

**Comment by valerojasm** [comment]
Hola!
Guardaste la carpeta entrega2 dentro de Sites y dentro de ella archivo.php?

**Comment by gnacrur** [comment]
Hola! Si, hice eso. En todo caso, estoy usando la app de la ayudantía, para asegurarme de que el .php que estoy usando esta bueno. Después lo voy a cambiar a nuestra app. 

UPDATE: Ahí me funcionó usando lo que dijeron en la ayudantía pero sin el archivo.php alfinal.

**Comment by RodrigoNazar** [comment]
Como lo hiciste al final @gnacrur ?, a mi tampoco me funciona :(
Pusiste:
bases.ing.puc.cl/~grupo12/entrega2 ?
