### ISSUE TITLE
BCNF y diagramas ER

### ISSUE THREAD

**Issue by dberezin** [IIC2413/Syllabus-2019-1#58]
Hola,
Supongamos que tengo una tabla, por ejemplo ciudad, y otra tabla región y dado que ciudad implica región a la tabla ciudad le agrego el ID de región en lugar de hacer una tercera tabla de relaciones.

Al momento de hacer el diagrama ER, debo mostrar como si existiera una relación entre ambos? O simplemente que ambos tengan el atributo ID de región sin estar conectados? Supongo que lo segundo, pero en este caso las relaciones uno a muchos nunca estarían en BCNF.

**Comment by valerojasm** [comment]
Hola! Claro que tienen relación, uno pertenece a otro, en este caso Ciudad pertenece a Región, o sea que una región puede poseer muchas ciudades, 1:N como dices.

Que una tabla tenga foreign keys no afecta necesariamente a su normalización. Te dejo [acá](https://dba.stackexchange.com/a/124403) una buena respuesta de SO sobre una pregunta por el estilo. De todas maneras, te recomiendo que te repases las clases de dependencias funcionales y que busques material para poder entenderlo mejor, hay muchos ejemplos que te pueden ayudar a que te quede más claro :blush:

Suerte!

**Comment by dberezin** [comment]
Ok, gracias! Estaba pensando la relación específicamente como los rombos en el diagrama ER (es decir, tablas que sean un Join entre las llaves).
