### ISSUE TITLE
Formato consultas 4, 5 y 6

### ISSUE THREAD

**Issue by JavierNarvaez** [IIC2413/Syllabus-2019-1#6]
Hola, ¿cómo se entregan las consultas 4, 5 y 6? ¿O para responderlas solamente es necesario que las tablas que hagamos sean consistentes para una posible consulta con álgebra relacional?

Gracias de antemano

**Comment by alanezz** [comment]
Hola,

Como se dijo en clases, las consultas 4, 5 y 6 tienen que pensarlas cómo las harían eventualmente en SQL. La idea es que mediten si es que su esquema las va a poder soportar en el futuro.

Saludos!
