### ISSUE TITLE
Duda Consulta 3 Grupo Pares

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2413/Syllabus-2019-1#60]
Hola! No me queda muy clara esta consulta que dice:

3. Dado un nombre de tour a viñas y una cepa de vino, entregue todos los nombres de
los vinos presentes en ese tour que sean de esa cepa.

En este caso tenemos que ver por cuales viñas pasa el tour y si en una de esas viñas se da un vino de la cepa que estamos buscando, y además ese vino está presente en el tour? O simplemente se debe revisar que vinos están presentes en el tour por la tabla entregada enovino y se entrega esto?

Muchas gracias de antemano!

**Comment by valerojasm** [comment]
Hola!

Son todos los vinos de esa cepa **presentes** en ese tour, no si las viñas de ese tour tienen esa cepa, ya que puede que la tengan pero no la ofrezcan en la degustación del tour. :blush:

Espero que te sirva!
Saludos
