### ISSUE TITLE
[Entrega 2] Detalles Académicos

### ISSUE THREAD

**Issue by msmendoza** [IIC2413/Syllabus-2019-1#61]
En esta sección se hace referencia a los elementos que debe contener el archivo `e2grupoxx.pdf` y mis dudas son las siguientes:

1.  El esquema de la base de datos no incluye las llaves foráneas (solo primarias), ¿correcto?. [refiriéndome al esquema como el enviado para la Entrega 1]
2.  Hay un punto que habla sobre las restricciones de las llaves de las tablas y otro sobre el código SQL utilizado para la creación de las tablas, pero pasa que al mostrar el código en el `.pdf` también estoy mostrando las llaves, ¿con eso basta o debo explicar/mencionar las llaves en un apartado diferente?
3. ¿Los comandos SQL de creación de tabla incluyen al código utilizado también para *poblarlas* o debemos solo incluir la parte de creación?

Finalmente (a pesar de lo ya preguntado) me pregunto si es posible entregar (subir al server) los siguientes archivos con sus respectivos apartados:

 * `e2grupoxx.pdf`: esquema, diagrama E/R, justificación de modelo BCNF, supuestos realizados.
* `e2grupoxx.sql`: código asociado a la parte de *table creation* y *table loading* (aquí se harían explícitas las llaves primarias y foráneas de las tablas).
* `e2grupoxx_queries.sql`: código asociado a las *queries* implementadas.
* `e2grupoxx.py`: código asociado a la parte de filtrado/limpieza/creación de los `.csv` necesarios para *poblar* las tablas (solo en caso de que el ayudante corrector quiera verlo, puesto que **no** es pedido por el enunciado)
* `README.md`: En caso de que se le quiera entregar amor al corrector y más información sobre los archivos.

Hago esta pregunta porque a mi juicio debería ser más fácil corregir código en una IDE especializada que en un `.pdf` que emula el código con determinado *environment* y puede tener errores de alineamiento o parecidos que finalmente terminan dificultando la lectura.

Como se puede ver es lo mismo que se pide en el enunciado, solo que distribuido de manera diferente. En caso de ser afirmativa la respuesta, se mantienen obviamente los mismos derechos de los correctores de "bajar nota" por archivos desordenados/mal explicados.

**No intento imponer ningún orden para los demás grupos, solo hago esta pregunta para ver si es posible facilitar la entrega del mío**

**Comment by valerojasm** [comment]
Hola! 

1. El esquema posee todos los atributos de la tabla. Las FK también lo son.

2. Sí, en el código queda claro cuáles son PK y FK, pero si lo vas a hacer así recuerda al menos introducirlo de esa manera (*A continuación dejamos el código para crear las tablas, el que también muestra las llaves que son PK/FK de cada una... etc*).

3. Tal como sale en el enunciado, el código para crear las tablas está bien, el que usaste para poblarlas no es necesario, pero puedes ponerlo si quieres.

Y respecto a tu última pregunta, el enunciado pide directamente un PDF, ya que eso es lo que se revisará. Puedes hacer un Markdown para que el código quede ordenado, soporta varios lenguajes para escribirlo, entre ellos sql. No te compliques :blush:, puedes hacerlo de la forma que te parezca más cómoda siempre y cuando sigas lo que te pide el enunciado.

Espero que resuelva tus dudas.
Suerte!
