### ISSUE TITLE
Problema psql 

### ISSUE THREAD

**Issue by javalenzuela3** [IIC2413/Syllabus-2019-1#62]
Hola, tengo un problema un poco (muy) malo con psql. Resulta que con el último cambio en la base de datos quise hacer DROP a la tabla de Reservas para subirla de nuevo para asegurarme que todos los datos estuvieran. El tema es que en un momento se desconectó el internet mientras lo hacía y ahora en psql no puedo hacer nada con esta tabla. No puedo Dropearla ni ver sus atributos. Solo se que existe.
<img width="349" alt="Captura de pantalla 2019-04-18 a la(s) 23 30 05" src="https://user-images.githubusercontent.com/37152992/56403954-ec5dca80-6231-11e9-8e62-296aeba9ce0a.png">
Muestro que esto es lo que ocurre. Tengo que cancelar la ejecución por que no responde a nada, en cambio cuando pido por ejemplo `SELECT uid FROM Usuarios;` si me lo muestra.
Por favor ayuda ;(

**Comment by javalenzuela3** [comment]
Encontré este link donde podría dar indicios de los que esta pasando, pero no se si es real. Y si es real, no se si yo deba acabar esas cosas :( https://dba.stackexchange.com/questions/217593/drop-table-taking-too-long

**Comment by alanezz** [comment]
Hola,

Si no es problema trata de crear una tabla Reservas2 o algo así y trabaja con esa. Para arreglar lo que te pasó hay que matar las transacciones que tienen tomada la tabla.

Saludos.

**Comment by csolguin** [comment]
Me pasa algo similar, intento DROPEAR una tabla, pero se queda pegado (lleva más de 6 horas), si no existe solucion para ello, ¿Hay alguna posibilidad de que simplemente  me restauren el servidor a su estado inicial?

**Comment by fhohlberg** [comment]
> Hola,
> 
> Si no es problema trata de crear una tabla Reservas2 o algo así y trabaja con esa. Para arreglar lo que te pasó hay que matar las transacciones que tienen tomada la tabla.
> 
> Saludos.

Nos paso lo mismo, también para la tabla reserva, y creamos una nueva tabla reservas2, sin embargo, no me deja reestablecer las foregn keys, y se me echaron a perder todas las consultas que las teníamos listas.. 

Por favor ayuda
