### ISSUE TITLE
CREATE VIEW php

### ISSUE THREAD

**Issue by gnacrur** [IIC2413/Syllabus-2019-1#63]
Hola, estaba intentando ejecutar una query en la que se usa CREATE VIEW y luego en esta misma query se utiliza esta vista en otra consulta. En psql no hay problema con hacer esto pero al intentarlo en php esto no funciona. ¿Hay alguna forma de hacer esto? De lo contrario ¿esta permitido dejar creadas tablas adicionales a las mencionadas en los esquemas, guardandolas en psql del servidor para que al hacer la consulta estas views ya estén creadas?

**Comment by alanezz** [comment]
Hola,

No debería haber ningún problema en crear vistas con php. Puedes ver [https://stackoverflow.com/questions/7689715/calling-mysql-create-view-using-php-code](aquí) un ejemplo pero con MySQL. Sin embargo te recomendaría evitar las vistas, dado que puedes anidar consultas.

Saludos.

**Comment by gnacrur** [comment]
Gracias por la respuesta profe! El problema era que tiraba error porque las vistas ya estaban creadas y entonces el query no retornaba nada. Por alguna razón no me resulta anidar las consultas en ciertos casos (anidar dentro de una consulta ya anidada).

**Comment by alanezz** [comment]
Te recomiendo que corras las consultas en PSQL sin pasar por PHP para que compruebes que efectivamente están correctas. Una vez que sepas que el resultado es no vacío y correcto, te pasas a PHP.

Saludos.

**Comment by gnacrur** [comment]
Ese es el procedimiento que hago siempre pero nunca logré hacerlo con esto, debe ser una sutileza. Voy a seguir intentándolo. Gracias!
