### ISSUE TITLE
Modelación [Regiones] [Grupo par]

### ISSUE THREAD

**Issue by bgsamilla** [IIC2413/Syllabus-2019-1#64]
Hola! 
Tengo una pregunta de modelación en relación a las regiones, y por ejemplo los parques.

Los parques pertenecen a una  (y solo a una) región y "según lo que dicta mi corazón" es razonable poner el id de la región en la tabla de los parques y así evitar crear una tabla intermedia entre los parques y las regiones (y también evitar joins extras).

En base a esto, ¿que seria lo correcto?, ¿debería crear igual la tabla intermedia?.
Discutimos algo similar en clases, pero no recuerdo la conclusión.

Si esta bien dejarlo así y el motivo de mi pregunta ¿como relaciono las regiones con los parques en el diagrama?

Saludos

**Comment by alanezz** [comment]
Hola,

Como dijimos en clases, cuando hay una relación de uno a muchos, es natural anexar la primary key a la tabla en vez de tener una tabla intermedia. Ojo que el diagrama se ve igual: **nunca** se conectan dos entidades directamente, siempre hay que pasar por la relación intermedia en el diagrama, pero esa relación intermedia no siempre implica la creación de una tabla.

Saludos.
