### ISSUE TITLE
Modelacion Relaciones

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2413/Syllabus-2019-1#65]
Supongamos que tengo un usuario y este puede escribir mensajes. Entonces se tendría una tabla intermedia que contiene id_usuario y id_mensaje.  en esa tabla tendría que ambos id son llaves y que  ademas ambas son Foreign keys. puede un atributo ser llave y foreign key al mismo tiempo?, como se podria decir eso en sql?
Gracias

**Comment by alanezz** [comment]
Hola,

En efecto se puede y es súper normal. Supón una relación intermedia `R(id1 int, id2 int)`. Se puede decir algo como esto:

```SQL
CREATE TABLE R(
  id1 int, id2 int,
  PRIMARY KEY(id1, id2),
  FOREIGN KEY(id1) REFERENCES Table1(id1),
  FOREIGN KEY(id2) REFERENCES Table2(id2)
)
```

En el que la llave primaría es `id1` e `id1` en conjunto, mientras que cada el `id1` hace referencia a `Table1` y el `id2` hace referencia a `Table2`.

Saludos.

**Comment by ljrodriguez1** [comment]
Perfecto, muchas gracias, eso vendría siendo como de modelan relaciones de muchos a muchos?.
También me surgió la duda si para relaciones de uno a muchos es necesario crear una tabla Intermedia, ya que sun está para mí sería más eficiente ya que nos ahorraríamos un join. Entonces no sé si para el diagrama debo poner esta tabla Intermedia o si la puedo omitir y dejar el ID en la otra tabla y lo mismo para la programación

**Comment by alanezz** [comment]
Hola,

Como lo discutimos en la clase de modelación, en caso de una relación 1 a muchos, es posible ahorrarse la tabla intermedia haciendo lo que señalas.

Saludos!
