### ISSUE TITLE
Duda Consulta 5 Grupo impar

### ISSUE THREAD

**Issue by jfacuse** [IIC2413/Syllabus-2019-1#66]
Hola! En la consulta 5 piden entregar la habitacion mas reservada de cada region, pero haciendolo me di cuenta de que todas las habitaciones de la base de datos tienen solamente 1 reserva excepto 1 habitacion. Entonces para las otras regiones que no tienen esa habitacion entregamos cualquier otra habitacion ? Ya que todas se han reservado una pura vez.

**Comment by alanezz** [comment]
Hola,

Tienes que hacer una consulta que responda lo que te pedimos independiente de la instancia. En caso de empate en el primer lugar puedes entregar la que estimes conveniente.

Saludos.
