### ISSUE TITLE
Duda Consulta 7 grupo impar

### ISSUE THREAD

**Issue by jfacuse** [IIC2413/Syllabus-2019-1#67]
Hola! Tnego una duda con la consulta 7: El precio total que piden es el valor de la habitacion que se esta reservando o tambien hay que considerar que tal larga es la reserva (y que sea como precio * cantidad de dias)?

**Comment by alanezz** [comment]
Hola,

Para sacar el total del precio de la reserva, esto depende de los días, por lo que tienes que considerar que tan larga es la reserva.

Saludos.
