### ISSUE TITLE
Base de datos Ayudantia 2

### ISSUE THREAD

**Issue by isavega** [IIC2413/Syllabus-2019-1#68]
Si subí la carpeta de Ayudantia al servidor (incluyendo la base de datos). Por que al hacer una consulta me sale este error? 

![image](https://user-images.githubusercontent.com/42187168/56449847-453e6900-62ed-11e9-9b2f-014338af056b.png)

**Comment by valerojasm** [comment]
Hola! Revisa si te falta un ; en la línea anterior (10) de ese archivo

**Comment by isavega** [comment]
No falta :(

![image](https://user-images.githubusercontent.com/42187168/56450294-f98ebe00-62f2-11e9-9a87-26bb7414052d.png)

Si hago la consulta de la altura no tira error pero no aparece nada.

![image](https://user-images.githubusercontent.com/42187168/56450306-16c38c80-62f3-11e9-86d8-54ac6db6331e.png)

**Comment by valerojasm** [comment]
Me refiero al código de tu consulta_tipo_nombre.php, la línea 10

**Comment by isavega** [comment]
Buena! Efectivamente ese era el error, ahora me queda como la segunda foto 😱

**Comment by valerojasm** [comment]
Creaste las tablas en la base de datos y las poblaste? Cambiaste las variables de conexion.php por tus datos? Puede que sea eso!

**Comment by isavega** [comment]
Muchas gracias!
