### ISSUE TITLE
Datos entrega 2

### ISSUE THREAD

**Issue by jncaceres** [IIC2413/Syllabus-2019-1#69]
Hola, soy de un grupo par, lo que pasa es que yo habia poblado mis tablas con los primeros datos que habian subido, ahora hace poco me di cuenta que hay unos datos distintos( creo que los modificaron), queria saber si es necesario tener los datos nuevos, o puedo dejarlo como lo tengo.

**Comment by valerojasm** [comment]
Hola!

Los datos cambiaron porque tenían un par de errores, por lo que sí, debes usar los datos nuevos.

Saludos!
