### ISSUE TITLE
Duda sobre consulta 3 y cepa de los vinos (Grupos Pares)

### ISSUE THREAD

**Issue by BFFV** [IIC2413/Syllabus-2019-1#70]
Hola!
Tengo un par de dudas respecto a los vinos y a la consulta 3:

1) El atributo cepa de cada vino viene siempre como un string que termina con un espacio vacío (ej: 'MALBEC ' en vez de 'MALBEC'). ¿Para la consulta 3, el nombre de la cepa que ingresarán al probarlo será también con un espacio en blanco al final (como en el csv de vino), o será el nombre sin el espacio en blanco?
2) Como hay varios vinos que tienen el mismo nombre, ¿es necesario que NO se repitan al mostrar los resultados de la consulta 3, o da lo mismo?

**Comment by alanezz** [comment]
Hola,

1) Lo vamos a probar sin espacio. Esto se soluciona fácil si ocupas LIKE en vez de igualdad.
2) Puedes suponer lo que estimes conveniente y anotarlo es tu readme.

Saludos.

**Comment by BFFV** [comment]
Gracias!
