### ISSUE TITLE
Duda Consulta 5 (Grupos Pares)

### ISSUE THREAD

**Issue by BFFV** [IIC2413/Syllabus-2019-1#71]
Hola!
¿En la consulta 5 se debe considerar el sendero más largo que tiene personas 'en ruta', o simplemente el sendero más largo en general?

**Comment by alanezz** [comment]
Hola,

Tienes que mostrar las **personas** que estén en ruta en el sendero más largo en general.

Saludos.

**Comment by BFFV** [comment]
Gracias!
