### ISSUE TITLE
Problema Descarga PSQL

### ISSUE THREAD

**Issue by felipegarcia98** [IIC2413/Syllabus-2019-1#73]
Buenas, resulta que tengo el problema de que el psql nunca termina de instalarse T_T. Siempre se queda pegado en la fase final durante horas y no sucede nada mas :C

Alguna idea-recomendación-solucion?

**Comment by cmp831** [comment]
Puedes describir mejor el problema? Que OS tienes y si hay algún error específico que se muestra?

**Comment by felipegarcia98** [comment]
i'm sorry. Soy Windows 10 y no muestra ningun problema, solo muestra la barrita de instalando eternamente (ahora volvere a intentarlo)

[Screenshot](http://prntscr.com/neqwq6)
5 hours later: [Screenshot](http://prntscr.com/nesibf)

**Comment by cmp831** [comment]
Qué raro, asegúrate de aceptar las ventanas de UAC, a veces quedan escondidos.

**Comment by felipegarcia98** [comment]
Tenemos Paaaatria 'eñores.
Entre que frenamos la sincronización de las nubes, el antivirus, steam, etc; entre el cambio de directorio y otros intentos, se ha logrado \o/
