### ISSUE TITLE
Problema conectandose a la base de datos

### ISSUE THREAD

**Issue by firulais33** [IIC2413/Syllabus-2019-1#74]
Hola,

Primero, en que puerto debería conectarme?
Estoy tratando en el puerto 5432, pero me dice que el password es incorrecto, cuando estoy seguro de que está bien.
Después traté en el puerto 22, pero ahí me lanza el error: "unknown protocol authentication from server..." Si alguien sabe que pasa se agradecería, gracias!

**Comment by cmp831** [comment]
Desde donde estás tratando de acceder tu base de datos? En tu consola o usando PHP? Si es en PHP, asegúrate que utilizes la contraseña de la base de datos, cual debe ser `grupoXX`
