### ISSUE TITLE
Respecto al tutorial de PSQL

### ISSUE THREAD

**Issue by aamedinaj** [IIC2413/Syllabus-2019-1#76]
Creo haber seguido bien los pasos para la instalación. Pero cuando intento crear el servidor, muchas combinaciones de nombre-dirección-contraseña-puerto fallaron y resultaron en errores de distinto tipo...podrían ser un poquito más explícitos en cómo se crea un server? 

Gracias

**Comment by alanezz** [comment]
Qué sistema operativo estás usando?

**Comment by aamedinaj** [comment]
Windows 10

**Comment by alanezz** [comment]
Se supone que cuando terminas de instalar puedes correr desde el pgAdmin la base de datos Postgres, y dejar andando el servidor. Si ves este [video](https://www.youtube.com/watch?v=e1MwsT5FJRQ) te quedará claro cómo dejar corriendo la base de datos y luego conectarte por línea de comandos.

Saludos.

**Comment by aamedinaj** [comment]
1. El tutorial me sirvio bastante
2. Probablemente habia tenido un error en la instalacion la primera vez, asi que barrí con todo, lo re-instalé y todo funciona
Gracias :D
