### ISSUE TITLE
Duda postrgresql crear "almacenados" actividad

### ISSUE THREAD

**Issue by gnacrur** [IIC2413/Syllabus-2019-1#77]
Hola, logré instalar exitosamente postgresql (por fin) y ahora al intentar usar createdb me pide una contraseña. Supongo que es la que te piden que pongas al instalar postgresql pero no me funciona. Estoy muy seguro que estoy poniendo la contraseña que puse cuando lo instale, alguna idea de que puede estar pasando?
Gracias de antemano.

**Comment by cmp831** [comment]
Si no mal recuerdo, las versiones nuevas de Postgres no creará el usuario por defecto que lleva el nombre de tu usuario del OS. Por lo que debes crear tu propio usuario y darle los permisos apropiados. 
Puedes seguir este excelente respuesta en stackoverflow para realizarlo
https://stackoverflow.com/a/37500607

**Comment by gnacrur** [comment]
Hola, al parecer eso no era porque no funcionó, alguna idea? Se que se entrega hoy el bonus pero de todos modos quiero hacer el jupyter a modo de estudio. Gracias!
