### ISSUE TITLE
Duda Entrega 2, comandos utilizados y uso de css e imagenes

### ISSUE THREAD

**Issue by dhvasquez** [IIC2413/Syllabus-2019-1#78]
Hola, queria saber si en el informe en la parte de los comandos, debemos poner cada comando utilizado por cada tabla, o podemos hacer un comando que represente todos?

Y para el orden de la pagina php, ¿es posible utilizar un archivo css para ordenar, y en la utilizacion de imagenes para agregarlo un poco mas de estilo a la página?

**Comment by valerojasm** [comment]
Hola! La idea es que muestres todos los comandos, para ver cómo declaraste cada una de las tablas con sus respectivos atributos. 

En cuanto a lo segundo, es completamente bienvenido que ocupes hojas de estilo (y hasta premiado) para tu entrega. 

Saludos!
