### ISSUE TITLE
Consulta 6 grupos impares

### ISSUE THREAD

**Issue by Franco1605** [IIC2413/Syllabus-2019-1#79]
Hola. En esta consulta me surgió la duda de si el usuario tiene que ingresar algún parámetro, o solo debo mostrar lo que me piden ahí (2da región, habitación más barata y qué usuarios la reservaron.
Gracias de antemano !

**Comment by ppotin** [comment]
Hola! 
Para esa consulta no es necesario que el usuario ingrese algún parámetro, basta con mostrar el resultado de la consulta cuando el usuario lo solicite. 

Saludos!
