### ISSUE TITLE
Problemas con las Consultas Grupo Impar/ Querys Vacías

### ISSUE THREAD

**Issue by arpincheira** [IIC2413/Syllabus-2019-1#82]
Hola, resulta ser que al subir las consultas al servidor estas retornan vacío si poseen dentro de ellas los comandos DATEDIFF, HAVING, MAX y MIN, he intentado arreglar el error de diversas maneras pero hasta ahora ese es el factor común, no se si no deberían usarse para las consultas o simplemente estoy haciendo algo mal :/

P.D. : Para la consulta en que usaba having simplemente anidé una consulta para evitar usar el comando y funcionó.

P.D. 2: Las consultas las probamos con mi compañero de grupo en sqlite y funcionan correctamente(por lo menos retornan algo las que no tienen DATEDIFF)

Muchas Gracias de antemano

**Comment by valerojasm** [comment]
Hola!

Eso es porque PostgreSQL no tiene la función DATEDIFF. La idea es que sus consultas siempre las vayan probando en el servidor para evitar estos problemas, de modo de asegurarse que cualquier recurso que ocupen sea soportado por postgres (cuando encuentren algo en internet, busquen eso también).

Te dejo [acá](http://www.sqlines.com/postgresql/how-to/datediff) más información de cómo replicar un DATEDIFF.

Saludos!
