### ISSUE TITLE
Enunciado llaves primarias y foráneas 

### ISSUE THREAD

**Issue by rafafdz** [IIC2413/Syllabus-2019-1#83]
Hola! En el enunciado aparece lo siguiente:
*```Debes asegurarte que tu modelo esté en BCNF y justificar esto mediante la descripción de las dependencias funcionales.```*

Para esta justificación, es suficiente que se muestre cuales son las dependencias funcionales de cada relación y mostrar que tu esquema tiene como llaves los atributos de cada dependencia que determinan a los demás?

Gracias!

**Comment by alanezz** [comment]
Hola,

Sí, basta con eso.

Saludos.
