### ISSUE TITLE
Estado del servidor bases.ing.puc.cl

### ISSUE THREAD

**Issue by hbkim94** [IIC2413/Syllabus-2019-1#84]
Hola!

Pasó algo con el host? No logro acceder a él.

De antemano gracias!

**Comment by rafafdz** [comment]
rip servidor

**Comment by lucasvsj** [comment]
F

**Comment by fjlopez7** [comment]
Thanos delete server

**Comment by alanezz** [comment]
Hola,

Publiqué en el SIDING lo que sucede. Les vamos a dar un día más para que esto no sea un problema.

Saludos.

pd. #DontSpoilTheEndgame

**Comment by hbkim94** [comment]
Hola,

Sigo teniendo problemas con el servidor. Pude acceder a él hoy pero está con muchísimo lag, o la conexión se resetea. Espero que puedan informarnos sobre el estado del server.

Saludos!

**Comment by Drpinto1** [comment]
Hola, me pasa lo mismo que a @hbkim94 y además el servidor se cae de forma esporádica :cry:

**Comment by raespinoza4** [comment]
Hola,

Me pasa exactamente lo mismo, el servidor esta muy lag y se esta cayendo de forma muy seguida :(
EDIT: Se volvio a caer 1 minuto despues de comentar :( no se alcanzan ni a subir los archivos

**Comment by lucasvsj** [comment]
Se volvio a caer 😭

**Comment by DaniOteiza** [comment]
Hola! 
También me pasa lo mismo :(. Se cae constantemente y no alcanzo a hacer las modificaciones.

**Comment by alanezz** [comment]
Hola,

Lamentablemente los servidores del dcc están con problemas desde ayer y al parecer no solucionaron los problemas. Voy a averiguar el lunes que es lo que pasa. Vamos a dejar los servidores abiertos para entregar hasta el lunes.

Saludos.
