### ISSUE TITLE
Dependencias Funcionales y Foreign Keys

### ISSUE THREAD

**Issue by FJavierOss** [IIC2413/Syllabus-2019-1#85]
Hola, tengo una duda respecto a como visualizar una dependencia funcional cuando hay foreign keys, poniendo un ejemplo 

>nombre_ciudad, región_id → num_habitantes,
>intendentes, coordenadas_geográficas

Pero tambien en otro tabla se tiene que:

> región_id → nombre_region, descripcion

Entonces mi duda es dado que region es llave tambien, y de otros atributos, se obvia el hecho y se trata la dependencia funcional como si fueran tablas separadas.

Y suponiendo el caso de que hubiera una tabla intermedia, donde se relacionan a las regiones con las ciudades. Por lo que se tendrían 3 tablas, la primera con las ciudades y su información, la segunda con las regiones y su información y la tercera como la tabla de intermedia de las dos.

Entonces la tabla intermedia como quedaria segun dependencia funcional? Con
> region_id, nombre_ciudad

Gracias de antemano :smile:

**Comment by alanezz** [comment]
Hola,

Las llaves foráneas sólo te dicen que algo debe estar en otra tabla, por lo que no influyen en las dependencias funcionales. Lo que tienes que hacer es que para cada tabla, debes listar sus dependencias funcionales.

Finalmente en la tabla intermedia se entiende que:

region_id, nombre_ciudad -> region_id, nombre_ciudad

Saludos.

**Comment by FJavierOss** [comment]
Ya bacán, gracias
