### ISSUE TITLE
Consultas corren en consola pero no en php

### ISSUE THREAD

**Issue by eitandv** [IIC2413/Syllabus-2019-1#86]
¡Hola!
Tenemos un problema con nuestra pagina en php. Poblamos la base de datos en el servidor y realizamos las consultas en la consola, lo que funcionaba perfecto, pero al momento de probar ciertas consultas en la aplicación PHP estas retornan vacías. 

Estamos seguros que esta todo igual al de los archivos ejemplos de la ayudantía, pero aun así no funciona. No se si sea legal publicar una foto de nuestro archivo de PHP por aquí, así que si necesitan verlo pídanlo nomas y se los envió al mail o algo por el estilo. 

¡Gracias por su tiempo!

**Comment by eitandv** [comment]
No importa, Error de tipeo. (Soy ...)

**Comment by isavega** [comment]
Puedo preguntar que error de tipeo? Porque me pasa exactamente lo mismo jajajaja

**Comment by eitandv** [comment]
Pucha hartos. Revisa las consultas. Cuando pongas variables strings tienes que ponerle las comillas en la consulta, PHP del servidor no te deja chantar una consulta anidada en el from sin un AS algo al final. Escribimos nmbre en vez de nombre (gracias por la hora perdida Moisés <3), etc. 

Si tienes algo más específico ponlo a ver si cacho jaja. 

Suerte!
