### ISSUE TITLE
Procedimientos almacenados y pauta de la I1

### ISSUE THREAD

**Issue by arpincheira** [IIC2413/Syllabus-2019-1#87]
Hola, quería preguntar 2 cosas:
La primera es sobre el enunciado del ejercicio propuesto en Procedimientos Almacenados 2 que dice: _Imagina ahora que tienes una instancia de la tabla Vuelo con miles de datos, y te interesan todos los lugares a los que puedes llegar volando desde Santiago, sin importar el número de escalas. ¿Puedes pensar en un algoritmo para implementar esto usando una función?_  A lo que se refiere es que, solo partiendo desde Santiago ponga todos los destinos posibles o que, dado que el vuelo comienza en Santiago y termina en una ciudad x y de esta puedes ir a n ciudades más que pueden o no poseer más vuelos que partan desde ahí, poner todas estas ciudades a las cuales se puede llegar? 

Mi segunda pregunta es con respecto a lo que dice la pauta de la pregunta 3 de la I1 vs lo que se dijo en una issue, resulta ser que en el enunciado especifica que se deben utilizar llaves foráneas en el modelo, pero en la issue https://github.com/IIC2413/Syllabus-2019-1/issues/31 aparece que no entraban como contenido de esta interrogación. Dado que en mi pregunta 3 por lo menos se hace referencia al no uso de llaves foráneas mi pregunta es: ¿Existió algún tipo de descuento relacionado a eso? (Update: Ya me la respondieron)

P.D.: Un ejemplo de la pregunta 1 es: tenemos un vuelo que va De Santiago a Concepción, uno que va desde Concepción a Dalas y otro que va De Santiago a Shangai, entonces mi consulta debería retornar Concepción, Dalas y Shangai o Concepción y Dalas solamente?

**Comment by alanezz** [comment]
Respecto a los procedimientos almacenados, debes retornar todos los alcanzables. Si hay un vuelo de Santiago a Concepción y de Concepción a Dallas, debes retornar también Santiago Dallas.

No había descuento por llaves foráneas en la I1.

Saludos!
