### ISSUE TITLE
Contactar otros grupos 

### ISSUE THREAD

**Issue by fjlopez7** [IIC2413/Syllabus-2019-1#89]
Podrían poner los correos de los integrantes de cada grupo para poder contactar con los otros integrantes del grupo (en especial para los que fueron juntados al azar).

**Comment by felipesilvadv** [comment]
Hola

Si ya está agregado en el drive, de los grupos, adjunto el  [link](https://docs.google.com/spreadsheets/d/1IWzSGWa6Hf0_hHwkglqf0w7Zs1EfZPBM9IxzO2llEFo/edit?usp=sharing)
Saludos
