### ISSUE TITLE
Nombre como un primary key

### ISSUE THREAD

**Issue by jgramsch** [IIC2413/Syllabus-2019-1#9]
Hola,
Valdrá la pena asumir que los nombres de los senderos son únicos en todas las reservas (como para hacerla primary key)? o le agregamos un atributo **sid** ? 
Nos interesa por que no sabemos en que formato recibiremos alguna base de datos futura para el proyecto.

Saludos!

**Comment by naquiroz** [comment]
Hola :wave:! Creo que no entiendo bien tu pregunta. Asumiré que con `reservas` te refieres a `registros`.

Tomando lo anterior en cuenta, **no puedes asumir eso**, dado que eso podría implicar ya sea que un usuario solo puede hacer un sendero una vez :thinking: , o que nadie mas puede hacer el sendero que ya hizo un usario :open_mouth: 
Espero haber respondido tu pregunta. Saludos!

PD: Igual deberías considerar tener _casi_ siempre un `id` para las entidades :smile:

**Comment by FJavierOss** [comment]
Sumandome a la pregunta anterior, si los senderos según la descripción entregada por el enunciado no parecen poseer un id en su tabla de datos, ¿se puede asumir que su nombre es único y hacerlo así para la tabla senderos?. Para asi no tener problemas a la hora de revisar la tabla de registros teniendo a senderos distintos pero con el mismo nombre. ¿O se tiene que agregar un atributo id para los senderos en su tabla? 
Saludos. :smile:

**Comment by jgramsch** [comment]
Me refería a la tabla con los senderos, Pueden haber dos senderos con el mismo nombre a lo largo de la base de datos como para hacer los nombres la pk? o es necesario agregar un id?

**Comment by alanezz** [comment]
Hola,

A pesar de que los nombres de los senderos van a ser únicos, personalmente prefiero entregarle un id numérico adicional.

Saludos.

**Comment by Mahund** [comment]
En conclusión tenemos que inferir (o crear) la existencia de un id por cada sendero?

**Comment by valerojasm** [comment]
Hola! Depende totalmente de ti (y de como pienses la entrega), pero como dice @alanezz, pese a que los nombres no se repitan en los archivos que les entregamos, en general es preferible tener un id numérico único que los identifique.
