### ISSUE TITLE
Procedimientos Almacenados Guía

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2413/Syllabus-2019-1#90]
Edit: Ya lo resolví, tomaba A y B como ya creadas

Hola! Tenía una duda en la parte 2 donde se hace la resta entre dos tablas. No entiendo como probar si la función esta correcta porque en ningún momento se define en la función que se ingresan dos tablas (la A y la B) creo. Entonces cual es el comando a utilizar?

Por ejemplo yo cree dos tablas A1 y B1, estoy intentando realizar:

SELECT * FROM restar(A1, B1)

Pero me salen problemas

**Comment by alanezz** [comment]
Hola,

Tienes que crear tu mismo las tablas y poblarlas con datos. No es necesario poblarla con procedimientos, basta con un insert into.

Saludos.
