### ISSUE TITLE
Uso de librerías/frameworks para el proyecto

### ISSUE THREAD

**Issue by FelipeBodelon** [IIC2413/Syllabus-2019-1#93]
Hola, me gustaría saber si se puede utilizar algún framework de php para la realización de las entregas futuras. En particular busco librerías/frameworks para manejar el tema del registro y login del usuario.  Encontré una llamada [UserSpice](https://userspice.com/) que maneja lo mencionado. Lo ideal sería que el framework no maneje la interacción con las bases de datos y creo que con esto se podría.

Además, ¿Cual es la política en cuanto a otros frameworks más extensos como CodeIgniter o Laravel?

**Comment by alanezz** [comment]
Hola,

No, no se puede usar ningún framework web de PHP. Tiene que ser siempre PHP plano.

Saludos.
