### ISSUE TITLE
Cómo me doy vuelta la chaqueta?

### ISSUE THREAD

**Issue by aamedinaj** [IIC2413/Syllabus-2019-1#95]
Con respecto a la entrega 3, donde tenemos que acceder a la BD de ambos grupos según corresponda, el PHP de la pagina va a estar en el servidor de uno de los 2 grupos, ¿cómo le hacemos para acceder a la base de datos de el otro grupo?

**Comment by cmp831** [comment]
Hola, pueden expandir el archivo `data.php` dentro de la carpeta config, para crear otro PHP Data Objects (PDO) en `conexion.php`.
Un ejemplo/idea será:
```PHP
// data.php
<?php
$DBgrupoA = 'grupoAA';
$DBuserA = 'grupoAA';
$DBpasswordA = 'AAAAAAAA';
$DBgrupoB = 'grupoBB';
$DBuserB = 'grupoBB';
$DBpasswordB = 'BBBBBB';
?>
```
```PHP
// conexion.php
<?php
  try {
    require('data.php'); #Pide las variables para conectarse a la base de datos.
    $dbAA = new PDO("pgsql:dbname=$DBgrupoA;host=localhost;port=5432;user=$DBuserA;password=$DBpasswordA");
    $dbBB = new PDO("pgsql:dbname=$DBgrupoB;host=localhost;port=5432;user=$DBuserB;password=$DBpasswordB");
  } catch (Exception $e) {
    echo "No se pudo conectar a la base de datos: $e";
  }
?>
```
Pueden reemplazar los `A` y `B` con sus numeros de grupos respectivos, y tendrán acceso a ambas bases de datos. Podrán usar el `$dbXX` para hacer consultas en la base de datos que corresponde.

PD: No estoy 100% seguro si el código funcionará, cualquier error pueden preguntar mas abajo.
