### ISSUE TITLE
[SSH] - Permission Denied

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2413/Syllabus-2019-1#96]
Hola, estaba intentando ingresar a la base de datos por medio de `ssh` para testear unas consultas, pero no podemos entrar ya que nos sale el siguiente mensaje:

![image](https://user-images.githubusercontent.com/37163344/57006389-6dac4a00-6bae-11e9-9cc4-72853e8a29e6.png)

No hemos cambiado la clave, ni nada por el estilo, por lo que no entendemos que es lo que está sucediendo. Ayuda por favor 😢

**Comment by alanezz** [comment]
Hola,

El servidor está cerrado por ahora, va a volver a estar abierto mañana a primera hora.

Saludos.

**Comment by Faalfaro** [comment]
Seguimos con el problema. 😢

**Comment by felipesilvadv** [comment]
Hola, el servidor esta abierto ahora.

Saludos
