### ISSUE TITLE
Duda sobre Preguntas de Procedimientos almacenados  I2

### ISSUE THREAD

**Issue by arpincheira** [IIC2413/Syllabus-2019-1#97]
Hola, resulta ser que observando la guía de la I2 e interrogaciones anteriores me di cuenta de que los enunciados no explicitan si se puede utilizar o no la creación de tablas temporales dentro de la base de datos  lo que complica bastante al momento de realizar el código para responder a las preguntas, entonces mi duda es la siguiente:
¿Nosotros debemos asumir que se puede o debemos crear métodos alternativos para responder a las preguntas?

Muchas Gracias de antemano

**Comment by alanezz** [comment]
Hola,

No hay problema con el uso de tablas temporales.

Saludos.
