### ISSUE TITLE
ayudantía I2 Recursión

### ISSUE THREAD

**Issue by arpincheira** [IIC2413/Syllabus-2019-1#98]
Hola, en ayudantía solo escribimos la función recursiva pero no lo pusimos como una consulta de variable C(costo), mi pregunta es: ¿Para poder escribirlo como consulta lo expresamos como procedimiento almacenado o solo escribir lo de la recursión en conjunto con sus restricciones es correcto?

Muchas gracias de antemano

**Comment by MarceloSaldias** [comment]
Hola!

**Comment by MarceloSaldias** [comment]
Hola!

La manera mas correcta es tal como mencionas, para que la consulta pueda recibir una variable desde el usuario, deberías poner la consulta recursiva dentro de un procedimiento almacenado.

Sin embargo, pueden asumir que la variable C(costo) ya viene definida desde antes y simplemente la utilizan en la recursión (como lo hicimos en la ayudantia)
