### ISSUE TITLE
Duda entrega 3 importar archivos php

### ISSUE THREAD

**Issue by arbiocanpion** [IIC2413/Syllabus-2019-1#99]
Hola! 
Tengo una duda respecto a si esta permitido usar el comando include en php, ya que si bien es cierto, importa un archivo, pero puede ser algo que yo mismo he hecho

**Comment by valerojasm** [comment]
Hola!

Te refieres a importar tú mismo un archivo que tú creaste? Si es ese el caso, obvio que sí.

Saludos!

**Comment by arbiocanpion** [comment]
Gracias!
